import { PrismaClient, ServiceCategory, BadgeType, ServiceStatus, IncidentSeverity } from "@prisma/client";

const prisma = new PrismaClient();

interface ServiceInput {
  slug: string;
  name: string;
  category: ServiceCategory;
  tier: number;
  defaultBadge: BadgeType;
  limitPhraseKey: string;
  websiteUrl: string;
  description: string;
  surfaces: Array<{
    slug: string;
    displayName: string;
    badgeOverride?: BadgeType;
    limitPhraseOverrideKey?: string;
  }>;
}

const badgePhrases = [
  {
    key: "STATUS_PAGE_SYNC_GENERIC",
    lang: "en" as const,
    text: "Synced from the official status page; experience may vary by region, account, or plan.",
  },
  {
    key: "LIVE_MONITORING_EU",
    lang: "en" as const,
    text: "Automatically monitored from the EU; some incidents may be regional or configuration-dependent.",
  },
  {
    key: "COMMUNITY_GENERIC",
    lang: "en" as const,
    text: "Based on community reports and public signals; accuracy may vary.",
  },
  {
    key: "CHINA_REGIONAL",
    lang: "en" as const,
    text: "Monitored from the EU; regional accessibility may impact results. Availability in China may differ.",
  },
];

const services: ServiceInput[] = [
  // LLMs / CHATBOTS (14)
  {
    slug: "openai",
    name: "OpenAI",
    category: "LLM",
    tier: 1,
    defaultBadge: "STATUS_PAGE_SYNC",
    limitPhraseKey: "STATUS_PAGE_SYNC_GENERIC",
    websiteUrl: "https://openai.com",
    description: "Creator of ChatGPT, GPT API, DALL-E, and Sora",
    surfaces: [
      { slug: "chatgpt", displayName: "ChatGPT" },
      { slug: "api", displayName: "OpenAI API" },
      { slug: "dall-e", displayName: "DALL-E" },
      { slug: "sora", displayName: "Sora" },
    ],
  },
  {
    slug: "anthropic",
    name: "Anthropic",
    category: "LLM",
    tier: 1,
    defaultBadge: "STATUS_PAGE_SYNC",
    limitPhraseKey: "STATUS_PAGE_SYNC_GENERIC",
    websiteUrl: "https://anthropic.com",
    description: "Creator of Claude AI assistant and Claude API",
    surfaces: [
      { slug: "claude", displayName: "Claude" },
      { slug: "api", displayName: "Claude API" },
      { slug: "claude-code", displayName: "Claude Code" },
    ],
  },
  {
    slug: "google-gemini",
    name: "Google Gemini",
    category: "LLM",
    tier: 1,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://gemini.google.com",
    description: "Google's multimodal AI model and chatbot",
    surfaces: [
      { slug: "web", displayName: "Gemini Web" },
      { slug: "api", displayName: "Gemini API" },
    ],
  },
  {
    slug: "mistral",
    name: "Mistral AI",
    category: "LLM",
    tier: 1,
    defaultBadge: "STATUS_PAGE_SYNC",
    limitPhraseKey: "STATUS_PAGE_SYNC_GENERIC",
    websiteUrl: "https://mistral.ai",
    description: "French AI company building open and commercial LLMs",
    surfaces: [
      { slug: "le-chat", displayName: "Le Chat" },
      { slug: "api", displayName: "Mistral API" },
    ],
  },
  {
    slug: "deepseek",
    name: "DeepSeek",
    category: "LLM",
    tier: 1,
    defaultBadge: "STATUS_PAGE_SYNC",
    limitPhraseKey: "STATUS_PAGE_SYNC_GENERIC",
    websiteUrl: "https://deepseek.com",
    description: "Chinese AI lab known for cost-efficient open-source models",
    surfaces: [
      { slug: "chat", displayName: "DeepSeek Chat" },
      { slug: "api", displayName: "DeepSeek API" },
    ],
  },
  {
    slug: "xai-grok",
    name: "xAI Grok",
    category: "LLM",
    tier: 1,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://x.ai",
    description: "Elon Musk's AI chatbot integrated with X (Twitter)",
    surfaces: [
      { slug: "web", displayName: "Grok Web" },
      { slug: "api", displayName: "Grok API" },
    ],
  },
  {
    slug: "cohere",
    name: "Cohere",
    category: "LLM",
    tier: 1,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://cohere.com",
    description: "Enterprise AI platform for text generation and embeddings",
    surfaces: [
      { slug: "api", displayName: "Cohere API" },
      { slug: "coral", displayName: "Coral Chat" },
    ],
  },
  {
    slug: "ai21",
    name: "AI21 Labs",
    category: "LLM",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://ai21.com",
    description: "Creator of Jamba models and enterprise AI solutions",
    surfaces: [{ slug: "api", displayName: "AI21 API" }],
  },
  {
    slug: "inflection-pi",
    name: "Inflection Pi",
    category: "LLM",
    tier: 2,
    defaultBadge: "COMMUNITY_REPORTS",
    limitPhraseKey: "COMMUNITY_GENERIC",
    websiteUrl: "https://pi.ai",
    description: "Personal AI assistant focused on emotional intelligence",
    surfaces: [{ slug: "web", displayName: "Pi Web" }],
  },
  {
    slug: "character-ai",
    name: "Character.AI",
    category: "LLM",
    tier: 2,
    defaultBadge: "COMMUNITY_REPORTS",
    limitPhraseKey: "COMMUNITY_GENERIC",
    websiteUrl: "https://character.ai",
    description: "Platform for creating and chatting with AI characters",
    surfaces: [
      { slug: "web", displayName: "Character.AI Web" },
      { slug: "app", displayName: "Character.AI App" },
    ],
  },
  {
    slug: "reka",
    name: "Reka AI",
    category: "LLM",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://reka.ai",
    description: "Multimodal AI models for enterprise and developers",
    surfaces: [{ slug: "api", displayName: "Reka API" }],
  },
  {
    slug: "baidu-ernie",
    name: "Baidu ERNIE Bot",
    category: "LLM",
    tier: 2,
    defaultBadge: "COMMUNITY_REPORTS",
    limitPhraseKey: "CHINA_REGIONAL",
    websiteUrl: "https://yiyan.baidu.com",
    description: "Baidu's AI chatbot powered by ERNIE large language model",
    surfaces: [{ slug: "web", displayName: "ERNIE Bot Web" }],
  },
  {
    slug: "alibaba-qwen",
    name: "Alibaba Qwen",
    category: "LLM",
    tier: 2,
    defaultBadge: "COMMUNITY_REPORTS",
    limitPhraseKey: "CHINA_REGIONAL",
    websiteUrl: "https://tongyi.aliyun.com",
    description: "Alibaba's Tongyi Qianwen multimodal AI assistant",
    surfaces: [
      { slug: "web", displayName: "Qwen Web" },
      { slug: "api", displayName: "Qwen API" },
    ],
  },
  {
    slug: "zhipu-chatglm",
    name: "Zhipu AI (ChatGLM)",
    category: "LLM",
    tier: 2,
    defaultBadge: "COMMUNITY_REPORTS",
    limitPhraseKey: "CHINA_REGIONAL",
    websiteUrl: "https://chatglm.cn",
    description: "Chinese AI lab building GLM series language models",
    surfaces: [{ slug: "web", displayName: "ChatGLM Web" }],
  },

  // SEARCH (4)
  {
    slug: "perplexity",
    name: "Perplexity",
    category: "SEARCH",
    tier: 1,
    defaultBadge: "STATUS_PAGE_SYNC",
    limitPhraseKey: "STATUS_PAGE_SYNC_GENERIC",
    websiteUrl: "https://perplexity.ai",
    description: "AI-powered search engine with real-time answers",
    surfaces: [
      { slug: "web", displayName: "Perplexity Web" },
      { slug: "api", displayName: "Perplexity API" },
    ],
  },
  {
    slug: "you-com",
    name: "You.com",
    category: "SEARCH",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://you.com",
    description: "AI-powered search engine with chat and research modes",
    surfaces: [{ slug: "web", displayName: "You.com Web" }],
  },
  {
    slug: "phind",
    name: "Phind",
    category: "SEARCH",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://phind.com",
    description: "AI search engine built for developers",
    surfaces: [{ slug: "web", displayName: "Phind Web" }],
  },
  {
    slug: "kagi",
    name: "Kagi",
    category: "SEARCH",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://kagi.com",
    description: "Premium ad-free search engine with AI features",
    surfaces: [{ slug: "web", displayName: "Kagi Search" }],
  },

  // INFRASTRUCTURE (10)
  {
    slug: "hugging-face",
    name: "Hugging Face",
    category: "INFRA",
    tier: 1,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://huggingface.co",
    description: "AI model hub and inference platform",
    surfaces: [
      { slug: "hub", displayName: "Hub" },
      { slug: "inference", displayName: "Inference API" },
    ],
  },
  {
    slug: "groq",
    name: "Groq",
    category: "INFRA",
    tier: 1,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://groq.com",
    description: "Ultra-fast AI inference with custom LPU hardware",
    surfaces: [{ slug: "api", displayName: "Groq API" }],
  },
  {
    slug: "together-ai",
    name: "Together AI",
    category: "INFRA",
    tier: 1,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://together.ai",
    description: "Cloud platform for running open-source AI models",
    surfaces: [{ slug: "api", displayName: "Together API" }],
  },
  {
    slug: "replicate",
    name: "Replicate",
    category: "INFRA",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://replicate.com",
    description: "Run and fine-tune open-source AI models in the cloud",
    surfaces: [
      { slug: "api", displayName: "Replicate API" },
      { slug: "web", displayName: "Replicate Web" },
    ],
  },
  {
    slug: "fireworks-ai",
    name: "Fireworks AI",
    category: "INFRA",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://fireworks.ai",
    description: "Fast and efficient AI model inference platform",
    surfaces: [{ slug: "api", displayName: "Fireworks API" }],
  },
  {
    slug: "cerebras",
    name: "Cerebras",
    category: "INFRA",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://cerebras.ai",
    description: "AI compute platform with wafer-scale inference engine",
    surfaces: [{ slug: "api", displayName: "Cerebras API" }],
  },
  {
    slug: "modal",
    name: "Modal",
    category: "INFRA",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://modal.com",
    description: "Serverless cloud for AI and data applications",
    surfaces: [{ slug: "api", displayName: "Modal API" }],
  },
  {
    slug: "aws-bedrock",
    name: "AWS Bedrock",
    category: "INFRA",
    tier: 1,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://aws.amazon.com/bedrock",
    description: "Amazon's managed service for foundation models",
    surfaces: [{ slug: "api", displayName: "Bedrock API" }],
  },
  {
    slug: "azure-openai",
    name: "Azure OpenAI",
    category: "INFRA",
    tier: 1,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://azure.microsoft.com/en-us/products/ai-services/openai-service",
    description: "Microsoft Azure's hosted OpenAI models service",
    surfaces: [{ slug: "api", displayName: "Azure OpenAI API" }],
  },
  {
    slug: "google-vertex",
    name: "Google Vertex AI",
    category: "INFRA",
    tier: 1,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://cloud.google.com/vertex-ai",
    description: "Google Cloud's unified AI and ML platform",
    surfaces: [{ slug: "api", displayName: "Vertex AI API" }],
  },

  // IMAGE GENERATION (8)
  {
    slug: "midjourney",
    name: "Midjourney",
    category: "IMAGE",
    tier: 1,
    defaultBadge: "COMMUNITY_REPORTS",
    limitPhraseKey: "COMMUNITY_GENERIC",
    websiteUrl: "https://midjourney.com",
    description: "AI image generation via Discord and web app",
    surfaces: [
      { slug: "app", displayName: "Midjourney App" },
      { slug: "discord", displayName: "Midjourney Discord Bot" },
    ],
  },
  {
    slug: "stability-ai",
    name: "Stability AI",
    category: "IMAGE",
    tier: 1,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://stability.ai",
    description: "Creator of Stable Diffusion and DreamStudio",
    surfaces: [
      { slug: "dreamstudio", displayName: "DreamStudio" },
      { slug: "api", displayName: "Stability API" },
    ],
  },
  {
    slug: "adobe-firefly",
    name: "Adobe Firefly",
    category: "IMAGE",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://firefly.adobe.com",
    description: "Adobe's generative AI for creative professionals",
    surfaces: [
      { slug: "web", displayName: "Firefly Web" },
      { slug: "api", displayName: "Firefly API" },
    ],
  },
  {
    slug: "leonardo-ai",
    name: "Leonardo AI",
    category: "IMAGE",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://leonardo.ai",
    description: "AI-powered creative platform for image generation",
    surfaces: [{ slug: "web", displayName: "Leonardo Web" }],
  },
  {
    slug: "ideogram",
    name: "Ideogram",
    category: "IMAGE",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://ideogram.ai",
    description: "AI image generator with strong text rendering",
    surfaces: [{ slug: "web", displayName: "Ideogram Web" }],
  },
  {
    slug: "canva-ai",
    name: "Canva AI",
    category: "IMAGE",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://canva.com",
    description: "Canva's AI-powered design and image generation tools",
    surfaces: [
      { slug: "magic-design", displayName: "Magic Design" },
      { slug: "text-to-image", displayName: "Text to Image" },
    ],
  },
  {
    slug: "flux",
    name: "Flux (Black Forest Labs)",
    category: "IMAGE",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://blackforestlabs.ai",
    description: "Open-source image generation model by Black Forest Labs",
    surfaces: [{ slug: "api", displayName: "Flux API" }],
  },
  {
    slug: "krea-ai",
    name: "Krea AI",
    category: "IMAGE",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://krea.ai",
    description: "Real-time AI image generation and enhancement",
    surfaces: [{ slug: "web", displayName: "Krea Web" }],
  },

  // VIDEO GENERATION (7)
  {
    slug: "runway",
    name: "Runway",
    category: "VIDEO",
    tier: 1,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://runwayml.com",
    description: "AI-powered creative tools for video generation (Gen-3)",
    surfaces: [
      { slug: "web", displayName: "Runway Web" },
      { slug: "api", displayName: "Runway API" },
    ],
  },
  {
    slug: "pika",
    name: "Pika",
    category: "VIDEO",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://pika.art",
    description: "AI video generation and editing platform",
    surfaces: [{ slug: "web", displayName: "Pika Web" }],
  },
  {
    slug: "luma-ai",
    name: "Luma AI",
    category: "VIDEO",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://lumalabs.ai",
    description: "Dream Machine — AI video and 3D generation",
    surfaces: [{ slug: "web", displayName: "Dream Machine" }],
  },
  {
    slug: "synthesia",
    name: "Synthesia",
    category: "VIDEO",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://synthesia.io",
    description: "AI video generation with virtual avatars",
    surfaces: [
      { slug: "web", displayName: "Synthesia Web" },
      { slug: "api", displayName: "Synthesia API" },
    ],
  },
  {
    slug: "heygen",
    name: "HeyGen",
    category: "VIDEO",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://heygen.com",
    description: "AI video creation with customizable avatars",
    surfaces: [{ slug: "web", displayName: "HeyGen Web" }],
  },
  {
    slug: "kling-ai",
    name: "Kling AI",
    category: "VIDEO",
    tier: 2,
    defaultBadge: "COMMUNITY_REPORTS",
    limitPhraseKey: "CHINA_REGIONAL",
    websiteUrl: "https://klingai.com",
    description: "Kuaishou's AI video generation platform",
    surfaces: [{ slug: "web", displayName: "Kling Web" }],
  },
  {
    slug: "minimax-hailuo",
    name: "MiniMax Hailuo",
    category: "VIDEO",
    tier: 2,
    defaultBadge: "COMMUNITY_REPORTS",
    limitPhraseKey: "CHINA_REGIONAL",
    websiteUrl: "https://hailuoai.video",
    description: "Chinese AI video generation platform by MiniMax",
    surfaces: [{ slug: "web", displayName: "Hailuo Video" }],
  },

  // AUDIO (5)
  {
    slug: "elevenlabs",
    name: "ElevenLabs",
    category: "AUDIO",
    tier: 1,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://elevenlabs.io",
    description: "AI voice synthesis and cloning platform",
    surfaces: [
      { slug: "web", displayName: "ElevenLabs Web" },
      { slug: "api", displayName: "ElevenLabs API" },
    ],
  },
  {
    slug: "suno",
    name: "Suno",
    category: "AUDIO",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://suno.com",
    description: "AI music generation from text prompts",
    surfaces: [{ slug: "web", displayName: "Suno Web" }],
  },
  {
    slug: "udio",
    name: "Udio",
    category: "AUDIO",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://udio.com",
    description: "AI music creation and generation platform",
    surfaces: [{ slug: "web", displayName: "Udio Web" }],
  },
  {
    slug: "assembly-ai",
    name: "AssemblyAI",
    category: "AUDIO",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://assemblyai.com",
    description: "AI speech-to-text and audio intelligence API",
    surfaces: [{ slug: "api", displayName: "AssemblyAI API" }],
  },
  {
    slug: "murf",
    name: "Murf AI",
    category: "AUDIO",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://murf.ai",
    description: "AI voice generator for professional voiceovers",
    surfaces: [{ slug: "web", displayName: "Murf Web" }],
  },

  // DEV TOOLS (8)
  {
    slug: "github-copilot",
    name: "GitHub Copilot",
    category: "DEV",
    tier: 1,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://github.com/features/copilot",
    description: "AI pair programmer by GitHub and OpenAI",
    surfaces: [
      { slug: "extension", displayName: "Copilot Extension" },
      { slug: "chat", displayName: "Copilot Chat" },
    ],
  },
  {
    slug: "cursor",
    name: "Cursor",
    category: "DEV",
    tier: 1,
    defaultBadge: "STATUS_PAGE_SYNC",
    limitPhraseKey: "STATUS_PAGE_SYNC_GENERIC",
    websiteUrl: "https://cursor.com",
    description: "AI-native code editor built for pair programming with AI",
    surfaces: [
      { slug: "app", displayName: "Cursor App" },
      { slug: "ai", displayName: "Cursor AI Features" },
    ],
  },
  {
    slug: "replit-ai",
    name: "Replit AI",
    category: "DEV",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://replit.com",
    description: "AI-powered coding platform and IDE in the browser",
    surfaces: [
      { slug: "web", displayName: "Replit IDE" },
      { slug: "ai", displayName: "Replit AI Agent" },
    ],
  },
  {
    slug: "codeium",
    name: "Codeium / Windsurf",
    category: "DEV",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://codeium.com",
    description: "Free AI code completion and Windsurf AI editor",
    surfaces: [
      { slug: "extension", displayName: "Codeium Extension" },
      { slug: "windsurf", displayName: "Windsurf Editor" },
    ],
  },
  {
    slug: "tabnine",
    name: "Tabnine",
    category: "DEV",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://tabnine.com",
    description: "AI code assistant with privacy-focused approach",
    surfaces: [{ slug: "extension", displayName: "Tabnine Extension" }],
  },
  {
    slug: "bolt-new",
    name: "Bolt.new",
    category: "DEV",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://bolt.new",
    description: "AI-powered full-stack web app builder in the browser",
    surfaces: [{ slug: "web", displayName: "Bolt.new Web" }],
  },
  {
    slug: "v0-vercel",
    name: "v0 by Vercel",
    category: "DEV",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://v0.dev",
    description: "AI-powered UI generation tool by Vercel",
    surfaces: [{ slug: "web", displayName: "v0 Web" }],
  },
  {
    slug: "lovable",
    name: "Lovable",
    category: "DEV",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://lovable.dev",
    description: "AI full-stack app builder from natural language",
    surfaces: [{ slug: "web", displayName: "Lovable Web" }],
  },

  // PRODUCTIVITY (4)
  {
    slug: "notion-ai",
    name: "Notion AI",
    category: "PRODUCTIVITY",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://notion.so",
    description: "AI writing and productivity features inside Notion",
    surfaces: [{ slug: "ai", displayName: "Notion AI Features" }],
  },
  {
    slug: "grammarly",
    name: "Grammarly AI",
    category: "PRODUCTIVITY",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://grammarly.com",
    description: "AI-powered writing assistant and grammar checker",
    surfaces: [
      { slug: "web", displayName: "Grammarly Web" },
      { slug: "extension", displayName: "Grammarly Extension" },
    ],
  },
  {
    slug: "otter-ai",
    name: "Otter.ai",
    category: "PRODUCTIVITY",
    tier: 2,
    defaultBadge: "LIVE_MONITORING",
    limitPhraseKey: "LIVE_MONITORING_EU",
    websiteUrl: "https://otter.ai",
    description: "AI meeting transcription and note-taking assistant",
    surfaces: [{ slug: "web", displayName: "Otter.ai Web" }],
  },
  {
    slug: "jasper",
    name: "Jasper AI",
    category: "PRODUCTIVITY",
    tier: 2,
    defaultBadge: "COMMUNITY_REPORTS",
    limitPhraseKey: "COMMUNITY_GENERIC",
    websiteUrl: "https://jasper.ai",
    description: "AI content creation platform for marketing teams",
    surfaces: [{ slug: "web", displayName: "Jasper Web" }],
  },

    // ==========================================
    // VAGUE 4 — LLM (7 nouveaux)
    // ==========================================
    {
      slug: "meta-llama",
      name: "Meta Llama",
      category: "LLM",
      tier: 1,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://llama.meta.com",
      description: "Meta's open-source large language model family",
      surfaces: [
        { slug: "web", displayName: "Llama Web" },
        { slug: "api", displayName: "Llama API" },
      ],
    },
    {
      slug: "microsoft-copilot",
      name: "Microsoft Copilot",
      category: "LLM",
      tier: 1,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://copilot.microsoft.com",
      description: "Microsoft's AI assistant powered by GPT-4",
      surfaces: [
        { slug: "web", displayName: "Copilot Web" },
        { slug: "app", displayName: "Copilot App" },
      ],
    },
    {
      slug: "poe",
      name: "Poe",
      category: "LLM",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://poe.com",
      description: "Quora's multi-model AI chat platform",
      surfaces: [
        { slug: "web", displayName: "Poe Web" },
        { slug: "app", displayName: "Poe App" },
      ],
    },
    {
      slug: "apple-intelligence",
      name: "Apple Intelligence",
      category: "LLM",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.apple.com/apple-intelligence/",
      description: "Apple's on-device and cloud AI features for iPhone, iPad, and Mac",
      surfaces: [{ slug: "device", displayName: "Apple Intelligence" }],
    },
    {
      slug: "amazon-nova",
      name: "Amazon Nova",
      category: "LLM",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://aws.amazon.com/ai/generative-ai/nova/",
      description: "Amazon's foundation models available via AWS Bedrock",
      surfaces: [{ slug: "api", displayName: "Nova API" }],
    },
    {
      slug: "copy-ai",
      name: "Copy.ai",
      category: "LLM",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.copy.ai",
      description: "AI-powered copywriting and content generation platform",
      surfaces: [{ slug: "web", displayName: "Copy.ai Web" }],
    },
    {
      slug: "writesonic",
      name: "Writesonic",
      category: "LLM",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://writesonic.com",
      description: "AI writing assistant for marketing and content creation",
      surfaces: [{ slug: "web", displayName: "Writesonic Web" }],
    },

    // ==========================================
    // VAGUE 4 — IA CHINOISES (8 nouveaux)
    // ==========================================
    {
      slug: "bytedance-doubao",
      name: "ByteDance Doubao",
      category: "LLM",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "CHINA_REGIONAL",
      websiteUrl: "https://www.doubao.com",
      description: "ByteDance's AI chatbot assistant (China)",
      surfaces: [{ slug: "web", displayName: "Doubao Web" }],
    },
    {
      slug: "moonshot-kimi",
      name: "Moonshot AI (Kimi)",
      category: "LLM",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "CHINA_REGIONAL",
      websiteUrl: "https://kimi.moonshot.cn",
      description: "Moonshot AI's long-context chatbot assistant",
      surfaces: [{ slug: "web", displayName: "Kimi Web" }],
    },
    {
      slug: "baichuan",
      name: "Baichuan AI",
      category: "LLM",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "CHINA_REGIONAL",
      websiteUrl: "https://www.baichuan-ai.com",
      description: "Chinese large language model company",
      surfaces: [{ slug: "web", displayName: "Baichuan Web" }],
    },
    {
      slug: "01-ai-yi",
      name: "01.AI (Yi)",
      category: "LLM",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "CHINA_REGIONAL",
      websiteUrl: "https://www.01.ai",
      description: "Kai-Fu Lee's AI company with Yi model series",
      surfaces: [{ slug: "web", displayName: "Yi Web" }],
    },
    {
      slug: "sensetime",
      name: "SenseTime SenseChat",
      category: "LLM",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "CHINA_REGIONAL",
      websiteUrl: "https://www.sensetime.com",
      description: "SenseTime's AI chatbot and computer vision platform",
      surfaces: [{ slug: "web", displayName: "SenseChat Web" }],
    },
    {
      slug: "iflytek-spark",
      name: "iFlytek Spark",
      category: "LLM",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "CHINA_REGIONAL",
      websiteUrl: "https://xinghuo.xfyun.cn",
      description: "iFlytek's AI assistant specializing in Chinese language",
      surfaces: [{ slug: "web", displayName: "Spark Web" }],
    },
    {
      slug: "tencent-hunyuan",
      name: "Tencent Hunyuan",
      category: "LLM",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "CHINA_REGIONAL",
      websiteUrl: "https://hunyuan.tencent.com",
      description: "Tencent's multimodal AI foundation model",
      surfaces: [{ slug: "web", displayName: "Hunyuan Web" }],
    },
    {
      slug: "vidu",
      name: "Vidu",
      category: "VIDEO",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "CHINA_REGIONAL",
      websiteUrl: "https://www.vidu.studio",
      description: "Shengshu Technology's AI video generation platform (China)",
      surfaces: [{ slug: "web", displayName: "Vidu Web" }],
    },

    // ==========================================
    // VAGUE 4 — IMAGE (6 nouveaux)
    // ==========================================
    {
      slug: "clipdrop",
      name: "Clipdrop",
      category: "IMAGE",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://clipdrop.co",
      description: "AI-powered image editing and generation tools by Stability AI",
      surfaces: [{ slug: "web", displayName: "Clipdrop Web" }],
    },
    {
      slug: "nightcafe",
      name: "NightCafe",
      category: "IMAGE",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://creator.nightcafe.studio",
      description: "AI art generation platform with multiple models",
      surfaces: [{ slug: "web", displayName: "NightCafe Web" }],
    },
    {
      slug: "playground-ai",
      name: "Playground AI",
      category: "IMAGE",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://playground.com",
      description: "Free AI image generation and editing platform",
      surfaces: [{ slug: "web", displayName: "Playground Web" }],
    },
    {
      slug: "craiyon",
      name: "Craiyon",
      category: "IMAGE",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.craiyon.com",
      description: "Free AI image generator (formerly DALL-E Mini)",
      surfaces: [{ slug: "web", displayName: "Craiyon Web" }],
    },
    {
      slug: "artbreeder",
      name: "Artbreeder",
      category: "IMAGE",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.artbreeder.com",
      description: "Collaborative AI art creation through image blending",
      surfaces: [{ slug: "web", displayName: "Artbreeder Web" }],
    },
    {
      slug: "figma-ai",
      name: "Figma AI",
      category: "IMAGE",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.figma.com",
      description: "AI-powered design features in Figma",
      surfaces: [{ slug: "web", displayName: "Figma AI Features" }],
    },

    // ==========================================
    // VAGUE 4 — VIDEO (3 nouveaux)
    // ==========================================
    {
      slug: "kaiber",
      name: "Kaiber",
      category: "VIDEO",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://kaiber.ai",
      description: "AI video generation and transformation platform",
      surfaces: [{ slug: "web", displayName: "Kaiber Web" }],
    },
    {
      slug: "haiper",
      name: "Haiper",
      category: "VIDEO",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://haiper.ai",
      description: "AI-powered video creation tool from ex-DeepMind researchers",
      surfaces: [{ slug: "web", displayName: "Haiper Web" }],
    },
    {
      slug: "viggle",
      name: "Viggle",
      category: "VIDEO",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://viggle.ai",
      description: "AI video animation and character motion platform",
      surfaces: [{ slug: "web", displayName: "Viggle Web" }],
    },

    // ==========================================
    // VAGUE 4 — AUDIO (6 nouveaux)
    // ==========================================
    {
      slug: "d-id",
      name: "D-ID",
      category: "AUDIO",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.d-id.com",
      description: "AI-powered talking avatar and video generation",
      surfaces: [{ slug: "web", displayName: "D-ID Web" }],
    },
    {
      slug: "descript",
      name: "Descript",
      category: "AUDIO",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.descript.com",
      description: "AI-powered audio and video editing with transcription",
      surfaces: [{ slug: "web", displayName: "Descript Web" }],
    },
    {
      slug: "play-ht",
      name: "Play.ht",
      category: "AUDIO",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://play.ht",
      description: "AI voice generator and text-to-speech platform",
      surfaces: [
        { slug: "web", displayName: "Play.ht Web" },
        { slug: "api", displayName: "Play.ht API" },
      ],
    },
    {
      slug: "resemble-ai",
      name: "Resemble AI",
      category: "AUDIO",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.resemble.ai",
      description: "AI voice cloning and speech synthesis platform",
      surfaces: [{ slug: "web", displayName: "Resemble Web" }],
    },
    {
      slug: "aiva",
      name: "AIVA",
      category: "AUDIO",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.aiva.ai",
      description: "AI music composition assistant",
      surfaces: [{ slug: "web", displayName: "AIVA Web" }],
    },
    {
      slug: "soundraw",
      name: "Soundraw",
      category: "AUDIO",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://soundraw.io",
      description: "AI music generator for content creators",
      surfaces: [{ slug: "web", displayName: "Soundraw Web" }],
    },

    // ==========================================
    // VAGUE 4 — DEV TOOLS (4 nouveaux)
    // ==========================================
    {
      slug: "jetbrains-ai",
      name: "JetBrains AI",
      category: "DEV",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.jetbrains.com/ai/",
      description: "AI assistant integrated into JetBrains IDEs",
      surfaces: [{ slug: "plugin", displayName: "JetBrains AI Plugin" }],
    },
    {
      slug: "sourcegraph-cody",
      name: "Sourcegraph Cody",
      category: "DEV",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://sourcegraph.com/cody",
      description: "AI coding assistant with full codebase context",
      surfaces: [{ slug: "web", displayName: "Cody Web" }],
    },
    {
      slug: "rytr",
      name: "Rytr",
      category: "DEV",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://rytr.me",
      description: "AI writing assistant for developers and marketers",
      surfaces: [{ slug: "web", displayName: "Rytr Web" }],
    },
    {
      slug: "sudowrite",
      name: "Sudowrite",
      category: "DEV",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.sudowrite.com",
      description: "AI writing tool for fiction authors and storytellers",
      surfaces: [{ slug: "web", displayName: "Sudowrite Web" }],
    },

    // ==========================================
    // VAGUE 4 — INFRA (5 nouveaux)
    // ==========================================
    {
      slug: "databricks",
      name: "Databricks",
      category: "INFRA",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.databricks.com",
      description: "Data and AI platform with DBRX and Mosaic ML",
      surfaces: [{ slug: "platform", displayName: "Databricks Platform" }],
    },
    {
      slug: "sambanova",
      name: "SambaNova",
      category: "INFRA",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://sambanova.ai",
      description: "AI chip and inference platform for enterprise",
      surfaces: [{ slug: "api", displayName: "SambaNova API" }],
    },
    {
      slug: "lambda-labs",
      name: "Lambda Labs",
      category: "INFRA",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://lambdalabs.com",
      description: "GPU cloud for AI training and inference",
      surfaces: [{ slug: "cloud", displayName: "Lambda Cloud" }],
    },
    {
      slug: "lepton-ai",
      name: "Lepton AI",
      category: "INFRA",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.lepton.ai",
      description: "Serverless AI inference platform",
      surfaces: [{ slug: "api", displayName: "Lepton API" }],
    },
    {
      slug: "baseten",
      name: "Baseten",
      category: "INFRA",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.baseten.co",
      description: "Infrastructure for deploying and serving ML models",
      surfaces: [{ slug: "api", displayName: "Baseten API" }],
    },

    // ==========================================
    // VAGUE 4 — PRODUCTIVITY (3 nouveaux)
    // ==========================================
    {
      slug: "framer-ai",
      name: "Framer AI",
      category: "PRODUCTIVITY",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.framer.com",
      description: "AI-powered website builder and design tool",
      surfaces: [{ slug: "web", displayName: "Framer Web" }],
    },
    {
      slug: "speechify",
      name: "Speechify",
      category: "PRODUCTIVITY",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://speechify.com",
      description: "AI text-to-speech reader for documents and articles",
      surfaces: [
        { slug: "web", displayName: "Speechify Web" },
        { slug: "app", displayName: "Speechify App" },
      ],
    },
    {
      slug: "vercel-ai",
      name: "Vercel AI SDK",
      category: "PRODUCTIVITY",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://sdk.vercel.ai",
      description: "Vercel's AI SDK for building AI-powered applications",
      surfaces: [{ slug: "web", displayName: "AI SDK" }],
    },

    // ==========================================
    // VAGUE 4 — SEARCH (1 nouveau)
    // ==========================================
    {
      slug: "anyscale",
      name: "Anyscale",
      category: "SEARCH",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.anyscale.com",
      description: "Platform for scaling AI applications with Ray",
      surfaces: [{ slug: "api", displayName: "Anyscale API" }],
    },

    // ==========================================
    // VAGUE 5 — LLM (12 nouveaux)
    // ==========================================
    {
      slug: "google-gemma",
      name: "Google Gemma",
      category: "LLM",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://ai.google.dev/gemma",
      description: "Google's open-source lightweight language model family",
      surfaces: [{ slug: "model", displayName: "Gemma Models" }],
    },
    {
      slug: "ibm-granite",
      name: "IBM Granite",
      category: "LLM",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.ibm.com/granite",
      description: "IBM's enterprise-ready open-source LLM family",
      surfaces: [{ slug: "api", displayName: "Granite API" }],
    },
    {
      slug: "falcon",
      name: "Falcon (TII)",
      category: "LLM",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://falconllm.tii.ae",
      description: "Technology Innovation Institute's open-source multilingual LLM",
      surfaces: [{ slug: "model", displayName: "Falcon Models" }],
    },
    {
      slug: "thinking-machines",
      name: "Thinking Machines Lab",
      category: "LLM",
      tier: 1,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://thinkingmachines.ai",
      description: "Mira Murati's AI lab building broadly capable systems ($2B seed)",
      surfaces: [{ slug: "api", displayName: "TML API" }],
    },
    {
      slug: "coze",
      name: "Coze",
      category: "LLM",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.coze.com",
      description: "ByteDance's AI chatbot building platform",
      surfaces: [{ slug: "web", displayName: "Coze Web" }],
    },
    {
      slug: "quillbot",
      name: "QuillBot",
      category: "LLM",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://quillbot.com",
      description: "AI-powered paraphrasing and writing assistant",
      surfaces: [{ slug: "web", displayName: "QuillBot Web" }],
    },
    {
      slug: "ai2-olmo",
      name: "AI2 OLMo",
      category: "LLM",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://allenai.org/olmo",
      description: "Allen Institute for AI's fully open language model",
      surfaces: [{ slug: "model", displayName: "OLMo Models" }],
    },
    {
      slug: "lmarena",
      name: "LMArena",
      category: "LLM",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://lmarena.ai",
      description: "LLM benchmarking platform with Chatbot Arena ($1.7B valuation)",
      surfaces: [{ slug: "web", displayName: "Arena Web" }],
    },
    {
      slug: "openrouter",
      name: "OpenRouter",
      category: "LLM",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://openrouter.ai",
      description: "Unified API for accessing multiple LLM providers",
      surfaces: [{ slug: "api", displayName: "OpenRouter API" }],
    },
    {
      slug: "ollama",
      name: "Ollama",
      category: "LLM",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://ollama.com",
      description: "Run LLMs locally — massively popular with developers",
      surfaces: [{ slug: "app", displayName: "Ollama App" }],
    },
    {
      slug: "lmstudio",
      name: "LM Studio",
      category: "LLM",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://lmstudio.ai",
      description: "Desktop app to run local LLMs with a chat UI",
      surfaces: [{ slug: "app", displayName: "LM Studio App" }],
    },
    {
      slug: "huawei-pangu",
      name: "Huawei Pangu",
      category: "LLM",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "CHINA_REGIONAL",
      websiteUrl: "https://www.huaweicloud.com",
      description: "Huawei's large language model and cloud AI platform",
      surfaces: [{ slug: "cloud", displayName: "Pangu Cloud" }],
    },

    // ==========================================
    // VAGUE 5 — IMAGE (6 nouveaux)
    // ==========================================
    {
      slug: "photoroom",
      name: "PhotoRoom",
      category: "IMAGE",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.photoroom.com",
      description: "AI photo editor for e-commerce — 150M+ downloads",
      surfaces: [{ slug: "web", displayName: "PhotoRoom Web" }, { slug: "app", displayName: "PhotoRoom App" }],
    },
    {
      slug: "openart",
      name: "OpenArt",
      category: "IMAGE",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://openart.ai",
      description: "AI art generator with multiple models and editing tools",
      surfaces: [{ slug: "web", displayName: "OpenArt Web" }],
    },
    {
      slug: "tensor-art",
      name: "Tensor.Art",
      category: "IMAGE",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://tensor.art",
      description: "Free AI image generation with Stable Diffusion models",
      surfaces: [{ slug: "web", displayName: "Tensor.Art Web" }],
    },
    {
      slug: "civitai",
      name: "Civitai",
      category: "IMAGE",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://civitai.com",
      description: "Community hub for AI image models, LoRAs, and generation",
      surfaces: [{ slug: "web", displayName: "Civitai Web" }],
    },
    {
      slug: "magnific",
      name: "Magnific AI",
      category: "IMAGE",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://magnific.ai",
      description: "AI image upscaler and enhancer for stunning quality",
      surfaces: [{ slug: "web", displayName: "Magnific Web" }],
    },
    {
      slug: "recraft",
      name: "Recraft",
      category: "IMAGE",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.recraft.ai",
      description: "AI design tool for generating vector art, icons, illustrations",
      surfaces: [{ slug: "web", displayName: "Recraft Web" }],
    },

    // ==========================================
    // VAGUE 5 — VIDEO (8 nouveaux)
    // ==========================================
    {
      slug: "sora",
      name: "OpenAI Sora",
      category: "VIDEO",
      tier: 1,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://sora.com",
      description: "OpenAI's text-to-video AI — viral TikTok content engine",
      surfaces: [{ slug: "web", displayName: "Sora Web" }],
    },
    {
      slug: "google-veo",
      name: "Google Veo",
      category: "VIDEO",
      tier: 1,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://deepmind.google/technologies/veo/",
      description: "Google DeepMind's video generation model with native audio",
      surfaces: [{ slug: "web", displayName: "Veo in AI Studio" }],
    },
    {
      slug: "veed",
      name: "VEED",
      category: "VIDEO",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.veed.io",
      description: "AI-powered online video editor — 10M+ users, $35M ARR",
      surfaces: [{ slug: "web", displayName: "VEED Web" }],
    },
    {
      slug: "vidnoz",
      name: "Vidnoz",
      category: "VIDEO",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.vidnoz.com",
      description: "AI video creation tool with avatars and templates",
      surfaces: [{ slug: "web", displayName: "Vidnoz Web" }],
    },
    {
      slug: "invideo",
      name: "InVideo",
      category: "VIDEO",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://invideo.io",
      description: "AI video maker for social media and marketing",
      surfaces: [{ slug: "web", displayName: "InVideo Web" }],
    },
    {
      slug: "magic-hour",
      name: "Magic Hour",
      category: "VIDEO",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://magichour.ai",
      description: "All-in-one AI creative suite with multiple video models",
      surfaces: [{ slug: "web", displayName: "Magic Hour Web" }],
    },
    {
      slug: "topaz-video",
      name: "Topaz Video AI",
      category: "VIDEO",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.topazlabs.com/topaz-video-ai",
      description: "AI video upscaling and enhancement — pro editors' favorite",
      surfaces: [{ slug: "app", displayName: "Topaz App" }],
    },
    {
      slug: "synthesys",
      name: "Synthesys",
      category: "VIDEO",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://synthesys.io",
      description: "AI avatars, voiceovers, and video generation platform",
      surfaces: [{ slug: "web", displayName: "Synthesys Web" }],
    },

    // ==========================================
    // VAGUE 5 — AUDIO (8 nouveaux)
    // ==========================================
    {
      slug: "fathom",
      name: "Fathom",
      category: "AUDIO",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://fathom.video",
      description: "AI meeting assistant — records, transcribes, and summarizes calls",
      surfaces: [{ slug: "web", displayName: "Fathom Web" }],
    },
    {
      slug: "krisp",
      name: "Krisp",
      category: "AUDIO",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://krisp.ai",
      description: "AI-powered noise cancellation and meeting transcription",
      surfaces: [{ slug: "app", displayName: "Krisp App" }],
    },
    {
      slug: "whisper-openai",
      name: "OpenAI Whisper",
      category: "AUDIO",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://openai.com/research/whisper",
      description: "OpenAI's open-source speech recognition model",
      surfaces: [{ slug: "api", displayName: "Whisper API" }],
    },
    {
      slug: "deepgram",
      name: "Deepgram",
      category: "AUDIO",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://deepgram.com",
      description: "AI speech-to-text and text-to-speech API platform",
      surfaces: [{ slug: "api", displayName: "Deepgram API" }],
    },
    {
      slug: "rev-ai",
      name: "Rev AI",
      category: "AUDIO",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.rev.com",
      description: "Transcription and captioning service with AI + human review",
      surfaces: [{ slug: "web", displayName: "Rev Web" }, { slug: "api", displayName: "Rev API" }],
    },
    {
      slug: "kits-ai",
      name: "Kits AI",
      category: "AUDIO",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.kits.ai",
      description: "AI voice cloning and conversion for musicians and creators",
      surfaces: [{ slug: "web", displayName: "Kits Web" }],
    },
    {
      slug: "voicemod",
      name: "Voicemod",
      category: "AUDIO",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.voicemod.net",
      description: "Real-time AI voice changer for gaming and streaming",
      surfaces: [{ slug: "app", displayName: "Voicemod App" }],
    },
    {
      slug: "moises",
      name: "Moises",
      category: "AUDIO",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://moises.ai",
      description: "AI-powered music practice app — stem separation and more",
      surfaces: [{ slug: "web", displayName: "Moises Web" }, { slug: "app", displayName: "Moises App" }],
    },

    // ==========================================
    // VAGUE 5 — DEV (9 nouveaux)
    // ==========================================
    {
      slug: "supermaven",
      name: "Supermaven",
      category: "DEV",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://supermaven.com",
      description: "Ultra-fast AI code completion — 40K+ developers",
      surfaces: [{ slug: "plugin", displayName: "Supermaven Plugin" }],
    },
    {
      slug: "aider",
      name: "Aider",
      category: "DEV",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://aider.chat",
      description: "Open-source AI pair programming in your terminal",
      surfaces: [{ slug: "cli", displayName: "Aider CLI" }],
    },
    {
      slug: "continue-dev",
      name: "Continue",
      category: "DEV",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://continue.dev",
      description: "Open-source AI code assistant for VS Code and JetBrains",
      surfaces: [{ slug: "plugin", displayName: "Continue Plugin" }],
    },
    {
      slug: "pieces",
      name: "Pieces for Developers",
      category: "DEV",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://pieces.app",
      description: "AI-powered developer productivity tool for code snippets",
      surfaces: [{ slug: "app", displayName: "Pieces App" }],
    },
    {
      slug: "val-town",
      name: "Val Town",
      category: "DEV",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://val.town",
      description: "Social website to write and deploy serverless functions with AI",
      surfaces: [{ slug: "web", displayName: "Val Town Web" }],
    },
    {
      slug: "stackblitz",
      name: "StackBlitz (Bolt)",
      category: "DEV",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://stackblitz.com",
      description: "Full-stack web development in the browser with AI",
      surfaces: [{ slug: "web", displayName: "StackBlitz Web" }],
    },
    {
      slug: "github-models",
      name: "GitHub Models",
      category: "DEV",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://github.com/marketplace/models",
      description: "GitHub's marketplace for testing and deploying AI models",
      surfaces: [{ slug: "web", displayName: "GitHub Models Web" }],
    },
    {
      slug: "codesandbox",
      name: "CodeSandbox",
      category: "DEV",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://codesandbox.io",
      description: "Cloud IDE with AI features for instant dev environments",
      surfaces: [{ slug: "web", displayName: "CodeSandbox Web" }],
    },
    {
      slug: "supabase-ai",
      name: "Supabase",
      category: "DEV",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://supabase.com",
      description: "Open-source Firebase alternative with AI SQL assistant",
      surfaces: [{ slug: "web", displayName: "Supabase Dashboard" }, { slug: "api", displayName: "Supabase API" }],
    },

    // ==========================================
    // VAGUE 5 — INFRA (9 nouveaux)
    // ==========================================
    {
      slug: "nvidia-nim",
      name: "NVIDIA NIM",
      category: "INFRA",
      tier: 1,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://build.nvidia.com",
      description: "NVIDIA's inference microservices for deploying AI models",
      surfaces: [{ slug: "api", displayName: "NIM API" }],
    },
    {
      slug: "coreweave",
      name: "CoreWeave",
      category: "INFRA",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.coreweave.com",
      description: "GPU cloud provider specialized for AI workloads",
      surfaces: [{ slug: "cloud", displayName: "CoreWeave Cloud" }],
    },
    {
      slug: "runpod",
      name: "RunPod",
      category: "INFRA",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.runpod.io",
      description: "GPU cloud for AI inference and training",
      surfaces: [{ slug: "web", displayName: "RunPod Web" }, { slug: "api", displayName: "RunPod API" }],
    },
    {
      slug: "scale-ai",
      name: "Scale AI",
      category: "INFRA",
      tier: 1,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://scale.com",
      description: "AI data platform for training data, evaluation, and fine-tuning",
      surfaces: [{ slug: "web", displayName: "Scale Platform" }],
    },
    {
      slug: "cloudflare-ai",
      name: "Cloudflare Workers AI",
      category: "INFRA",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://ai.cloudflare.com",
      description: "Run AI models at the edge with Cloudflare's global network",
      surfaces: [{ slug: "api", displayName: "Workers AI" }],
    },
    {
      slug: "paperspace",
      name: "Paperspace",
      category: "INFRA",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.paperspace.com",
      description: "GPU cloud for ML — notebooks, training, deployment",
      surfaces: [{ slug: "web", displayName: "Paperspace Web" }],
    },
    {
      slug: "vast-ai",
      name: "Vast.ai",
      category: "INFRA",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://vast.ai",
      description: "Marketplace for renting GPU compute at low prices",
      surfaces: [{ slug: "web", displayName: "Vast.ai Web" }],
    },
    {
      slug: "bentoml",
      name: "BentoML",
      category: "INFRA",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.bentoml.com",
      description: "Open-source framework for serving ML models in production",
      surfaces: [{ slug: "cloud", displayName: "BentoCloud" }],
    },
    {
      slug: "banana-dev",
      name: "Banana.dev",
      category: "INFRA",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.banana.dev",
      description: "Serverless GPU infrastructure for ML model deployment",
      surfaces: [{ slug: "api", displayName: "Banana API" }],
    },

    // ==========================================
    // VAGUE 5 — SEARCH (8 nouveaux)
    // ==========================================
    {
      slug: "exa-ai",
      name: "Exa",
      category: "SEARCH",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://exa.ai",
      description: "AI-powered search engine built for LLMs and AI apps",
      surfaces: [{ slug: "api", displayName: "Exa API" }],
    },
    {
      slug: "tavily",
      name: "Tavily",
      category: "SEARCH",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://tavily.com",
      description: "Search API optimized for AI agents and RAG",
      surfaces: [{ slug: "api", displayName: "Tavily API" }],
    },
    {
      slug: "brave-search-ai",
      name: "Brave Search AI",
      category: "SEARCH",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://search.brave.com",
      description: "Privacy-focused search with AI-powered answers",
      surfaces: [{ slug: "web", displayName: "Brave Search Web" }],
    },
    {
      slug: "andi-search",
      name: "Andi",
      category: "SEARCH",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://andisearch.com",
      description: "AI-powered conversational search engine",
      surfaces: [{ slug: "web", displayName: "Andi Web" }],
    },
    {
      slug: "pinecone",
      name: "Pinecone",
      category: "SEARCH",
      tier: 1,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.pinecone.io",
      description: "Vector database for AI — the most popular RAG infrastructure",
      surfaces: [{ slug: "api", displayName: "Pinecone API" }, { slug: "web", displayName: "Pinecone Console" }],
    },
    {
      slug: "weaviate",
      name: "Weaviate",
      category: "SEARCH",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://weaviate.io",
      description: "Open-source vector database for AI applications",
      surfaces: [{ slug: "cloud", displayName: "Weaviate Cloud" }],
    },
    {
      slug: "qdrant",
      name: "Qdrant",
      category: "SEARCH",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://qdrant.tech",
      description: "High-performance vector database for similarity search",
      surfaces: [{ slug: "cloud", displayName: "Qdrant Cloud" }],
    },
    {
      slug: "elastic-ai",
      name: "Elastic AI Search",
      category: "SEARCH",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.elastic.co",
      description: "Enterprise search with AI-powered relevance and vector search",
      surfaces: [{ slug: "cloud", displayName: "Elastic Cloud" }],
    },

    // ==========================================
    // VAGUE 5 — PRODUCTIVITY (10 nouveaux)
    // ==========================================
    {
      slug: "slack-ai",
      name: "Slack AI",
      category: "PRODUCTIVITY",
      tier: 1,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://slack.com/features/ai",
      description: "AI-powered summaries, search, and workflows in Slack",
      surfaces: [{ slug: "web", displayName: "Slack AI Features" }],
    },
    {
      slug: "zoom-ai",
      name: "Zoom AI Companion",
      category: "PRODUCTIVITY",
      tier: 1,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://zoom.us/ai-assistant",
      description: "AI meeting summaries, action items, and smart compose in Zoom",
      surfaces: [{ slug: "web", displayName: "Zoom AI" }],
    },
    {
      slug: "atlassian-ai",
      name: "Atlassian Intelligence",
      category: "PRODUCTIVITY",
      tier: 1,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.atlassian.com/platform/ai",
      description: "AI features across Jira, Confluence, and Atlassian products",
      surfaces: [{ slug: "jira", displayName: "Jira AI" }, { slug: "confluence", displayName: "Confluence AI" }],
    },
    {
      slug: "clickup-ai",
      name: "ClickUp AI",
      category: "PRODUCTIVITY",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://clickup.com/ai",
      description: "AI assistant for project management, docs, and tasks",
      surfaces: [{ slug: "web", displayName: "ClickUp AI" }],
    },
    {
      slug: "monday-ai",
      name: "Monday AI",
      category: "PRODUCTIVITY",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://monday.com/product/ai",
      description: "AI assistant for work management and automations",
      surfaces: [{ slug: "web", displayName: "Monday AI" }],
    },
    {
      slug: "linear-ai",
      name: "Linear",
      category: "PRODUCTIVITY",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://linear.app",
      description: "Modern project management with AI features — loved by devs",
      surfaces: [{ slug: "web", displayName: "Linear Web" }],
    },
    {
      slug: "airtable-ai",
      name: "Airtable AI",
      category: "PRODUCTIVITY",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://airtable.com",
      description: "AI-powered database and app building platform",
      surfaces: [{ slug: "web", displayName: "Airtable Web" }],
    },
    {
      slug: "miro-ai",
      name: "Miro AI",
      category: "PRODUCTIVITY",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://miro.com",
      description: "AI-powered collaborative whiteboard for teams",
      surfaces: [{ slug: "web", displayName: "Miro Web" }],
    },
    {
      slug: "tome",
      name: "Tome",
      category: "PRODUCTIVITY",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://tome.app",
      description: "AI-powered storytelling and presentation platform",
      surfaces: [{ slug: "web", displayName: "Tome Web" }],
    },
    {
      slug: "coda-ai",
      name: "Coda AI",
      category: "PRODUCTIVITY",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://coda.io",
      description: "AI-powered collaborative docs, spreadsheets, and workflows",
      surfaces: [{ slug: "web", displayName: "Coda Web" }],
    },

    // ==========================================
    // VAGUE 5 — AGENTS (14 nouveaux — NOUVELLE CATÉGORIE)
    // ==========================================
    {
      slug: "devin",
      name: "Devin (Cognition)",
      category: "AGENTS",
      tier: 1,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://devin.ai",
      description: "The first autonomous AI software engineer",
      surfaces: [{ slug: "web", displayName: "Devin Web" }],
    },
    {
      slug: "claude-code",
      name: "Claude Code",
      category: "AGENTS",
      tier: 1,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://docs.anthropic.com/en/docs/claude-code",
      description: "Anthropic's agentic coding tool from the terminal",
      surfaces: [{ slug: "cli", displayName: "Claude Code CLI" }],
    },
    {
      slug: "zapier-ai",
      name: "Zapier AI",
      category: "AGENTS",
      tier: 1,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://zapier.com/ai",
      description: "AI automations and AI actions in the most popular automation tool",
      surfaces: [{ slug: "web", displayName: "Zapier AI" }],
    },
    {
      slug: "make-ai",
      name: "Make (ex-Integromat)",
      category: "AGENTS",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.make.com",
      description: "Visual no-code automation platform with AI integrations",
      surfaces: [{ slug: "web", displayName: "Make Web" }],
    },
    {
      slug: "n8n",
      name: "n8n",
      category: "AGENTS",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://n8n.io",
      description: "Open-source workflow automation with AI agent capabilities",
      surfaces: [{ slug: "cloud", displayName: "n8n Cloud" }],
    },
    {
      slug: "langchain",
      name: "LangChain",
      category: "AGENTS",
      tier: 1,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://langchain.com",
      description: "The #1 framework for building LLM-powered agents and apps",
      surfaces: [{ slug: "web", displayName: "LangSmith" }, { slug: "api", displayName: "LangChain API" }],
    },
    {
      slug: "llamaindex",
      name: "LlamaIndex",
      category: "AGENTS",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.llamaindex.ai",
      description: "Data framework for building RAG and agent applications",
      surfaces: [{ slug: "cloud", displayName: "LlamaCloud" }],
    },
    {
      slug: "crewai",
      name: "CrewAI",
      category: "AGENTS",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.crewai.com",
      description: "Multi-agent AI framework for orchestrating role-based agents",
      surfaces: [{ slug: "web", displayName: "CrewAI Web" }],
    },
    {
      slug: "dify",
      name: "Dify",
      category: "AGENTS",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://dify.ai",
      description: "Open-source LLM app builder with agent workflows",
      surfaces: [{ slug: "cloud", displayName: "Dify Cloud" }],
    },
    {
      slug: "flowise",
      name: "Flowise",
      category: "AGENTS",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://flowiseai.com",
      description: "No-code LangChain — drag & drop LLM flow builder",
      surfaces: [{ slug: "web", displayName: "Flowise Web" }],
    },
    {
      slug: "botpress",
      name: "Botpress",
      category: "AGENTS",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://botpress.com",
      description: "AI chatbot and agent builder platform",
      surfaces: [{ slug: "web", displayName: "Botpress Web" }],
    },
    {
      slug: "voiceflow",
      name: "Voiceflow",
      category: "AGENTS",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.voiceflow.com",
      description: "Conversational AI agent builder for product teams",
      surfaces: [{ slug: "web", displayName: "Voiceflow Web" }],
    },
    {
      slug: "autogen",
      name: "AutoGen (Microsoft)",
      category: "AGENTS",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://microsoft.github.io/autogen/",
      description: "Microsoft's open-source multi-agent framework",
      surfaces: [{ slug: "framework", displayName: "AutoGen Framework" }],
    },
    {
      slug: "retool-ai",
      name: "Retool AI",
      category: "AGENTS",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://retool.com/products/ai",
      description: "Build internal AI-powered apps and agents with Retool",
      surfaces: [{ slug: "web", displayName: "Retool Web" }],
    },

    // ==========================================
    // VAGUE 5 — DESIGN (8 nouveaux — NOUVELLE CATÉGORIE)
    // ==========================================
    {
      slug: "capcut",
      name: "CapCut",
      category: "DESIGN",
      tier: 1,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.capcut.com",
      description: "ByteDance's all-in-one video editor with AI features — massive search volume",
      surfaces: [{ slug: "web", displayName: "CapCut Web" }, { slug: "app", displayName: "CapCut App" }],
    },
    {
      slug: "adobe-photoshop-ai",
      name: "Adobe Photoshop AI",
      category: "DESIGN",
      tier: 1,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.adobe.com/products/photoshop.html",
      description: "Generative Fill, Generative Expand, and AI features in Photoshop",
      surfaces: [{ slug: "app", displayName: "Photoshop AI" }],
    },
    {
      slug: "adobe-express",
      name: "Adobe Express",
      category: "DESIGN",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.adobe.com/express/",
      description: "Quick AI-powered design and content creation by Adobe",
      surfaces: [{ slug: "web", displayName: "Express Web" }],
    },
    {
      slug: "figma",
      name: "Figma",
      category: "DESIGN",
      tier: 1,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.figma.com",
      description: "Collaborative design tool with AI features — 'Figma down' is a huge search",
      surfaces: [{ slug: "web", displayName: "Figma Web" }, { slug: "ai", displayName: "Figma AI" }],
    },
    {
      slug: "framer",
      name: "Framer",
      category: "DESIGN",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.framer.com",
      description: "AI-powered website builder and design tool",
      surfaces: [{ slug: "web", displayName: "Framer Web" }],
    },
    {
      slug: "webflow-ai",
      name: "Webflow AI",
      category: "DESIGN",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://webflow.com",
      description: "Professional website builder with AI-assisted design",
      surfaces: [{ slug: "web", displayName: "Webflow Web" }],
    },
    {
      slug: "gamma",
      name: "Gamma",
      category: "DESIGN",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://gamma.app",
      description: "AI-powered presentations, documents, and webpages — 60M+ decks created",
      surfaces: [{ slug: "web", displayName: "Gamma Web" }],
    },
    {
      slug: "beautiful-ai",
      name: "Beautiful.ai",
      category: "DESIGN",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.beautiful.ai",
      description: "AI-powered presentation software with smart design rules",
      surfaces: [{ slug: "web", displayName: "Beautiful.ai Web" }],
    },

    // ==========================================
    // VAGUE 5 — THREE_D (6 nouveaux — NOUVELLE CATÉGORIE)
    // ==========================================
    {
      slug: "meshy",
      name: "Meshy",
      category: "THREE_D",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.meshy.ai",
      description: "Text-to-3D and image-to-3D AI generation platform",
      surfaces: [{ slug: "web", displayName: "Meshy Web" }],
    },
    {
      slug: "tripo3d",
      name: "Tripo AI",
      category: "THREE_D",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://tripo3d.ai",
      description: "Fast text-to-3D model generation for game assets and more",
      surfaces: [{ slug: "web", displayName: "Tripo Web" }],
    },
    {
      slug: "spline-ai",
      name: "Spline AI",
      category: "THREE_D",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://spline.design",
      description: "3D design tool for the web with AI generation features",
      surfaces: [{ slug: "web", displayName: "Spline Web" }],
    },
    {
      slug: "kaedim",
      name: "Kaedim",
      category: "THREE_D",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.kaedim3d.com",
      description: "Turn 2D images into production-ready 3D assets with AI",
      surfaces: [{ slug: "web", displayName: "Kaedim Web" }],
    },
    {
      slug: "wonder-dynamics",
      name: "Wonder Dynamics",
      category: "THREE_D",
      tier: 2,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.wonderdynamics.com",
      description: "AI-powered VFX and CG character animation (Autodesk)",
      surfaces: [{ slug: "web", displayName: "Wonder Studio" }],
    },
    {
      slug: "move-ai",
      name: "Move.ai",
      category: "THREE_D",
      tier: 3,
      defaultBadge: "COMMUNITY_REPORTS",
      limitPhraseKey: "COMMUNITY_GENERIC",
      websiteUrl: "https://www.move.ai",
      description: "AI-powered markerless motion capture from video",
      surfaces: [{ slug: "web", displayName: "Move.ai Web" }],
    },
];

const realisticIncidents = [
  {
    serviceSlug: "openai",
    title: "ChatGPT elevated error rates",
    severity: "MAJOR" as const,
    summary: "Users reported increased error rates and slow responses on ChatGPT. The issue was resolved after 45 minutes.",
    startedAt: new Date("2026-02-25T14:30:00Z"),
    resolvedAt: new Date("2026-02-25T15:15:00Z"),
  },
  {
    serviceSlug: "anthropic",
    title: "Claude API intermittent 503 errors",
    severity: "MINOR" as const,
    summary: "Some API users experienced intermittent 503 errors. Anthropic's team identified and fixed the issue.",
    startedAt: new Date("2026-02-20T09:00:00Z"),
    resolvedAt: new Date("2026-02-20T09:45:00Z"),
  },
  {
    serviceSlug: "google-gemini",
    title: "Gemini API degraded performance",
    severity: "MINOR" as const,
    summary: "Gemini API responses were slower than usual for approximately 2 hours.",
    startedAt: new Date("2026-02-22T18:00:00Z"),
    resolvedAt: new Date("2026-02-22T20:00:00Z"),
  },
  {
    serviceSlug: "midjourney",
    title: "Midjourney queue delays",
    severity: "MINOR" as const,
    summary: "Image generation queue times increased significantly. The backlog was cleared after scaling adjustments.",
    startedAt: new Date("2026-02-18T11:00:00Z"),
    resolvedAt: new Date("2026-02-18T13:30:00Z"),
  },
];

async function main() {
  console.log("🌱 Starting seed...");

  // Clean up database
  await prisma.communityReport.deleteMany({});
  await prisma.incident.deleteMany({});
  await prisma.observation.deleteMany({});
  await prisma.serviceSurface.deleteMany({});
  await prisma.service.deleteMany({});
  await prisma.region.deleteMany({});
  await prisma.badgePhrase.deleteMany({});

  // Seed badge phrases
  console.log("📝 Seeding badge phrases...");
  await prisma.badgePhrase.createMany({
    data: badgePhrases,
  });

  // Seed region (EU)
  console.log("🌍 Seeding region...");
  const region = await prisma.region.create({
    data: {
      code: "EU",
      displayName: "Europe (EU)",
    },
  });

  // Seed services and surfaces
  console.log("🚀 Seeding 201 services with surfaces...");
  const createdServices: Array<any> = [];

  for (const service of services) {
    const { surfaces, ...serviceData } = service;

    // Create service
    const createdService = await prisma.service.create({
      data: {
        ...serviceData,
        surfaces: {
          create: surfaces.map((surface) => ({
            slug: surface.slug,
            displayName: surface.displayName,
            badgeOverride: surface.badgeOverride,
            limitPhraseOverrideKey: surface.limitPhraseOverrideKey,
          })),
        },
      },
      include: {
        surfaces: true,
      },
    });

    createdServices.push(createdService);
  }

  console.log(`✅ Created ${createdServices.length} services`);

  // Seed observations (48 hours, 15-minute intervals = 192 observations per surface)
  console.log("📊 Seeding observations (48 hours, ~192 per surface)...");

  const observationsToCreate = [];
  const now = new Date();

  for (const service of createdServices) {
    for (const surface of service.surfaces) {
      // Generate 192 observations (48h / 15min = 192)
      for (let i = 0; i < 192; i++) {
        const observedAt = new Date(now.getTime() - i * 15 * 60 * 1000);

        // Realistic distribution: 95% OPERATIONAL, 3% DEGRADED, 2% OUTAGE
        const rand = Math.random();
        let status: ServiceStatus;
        let latencyMs: number | null;

        if (rand < 0.95) {
          status = "OPERATIONAL";
          latencyMs = Math.floor(Math.random() * 300) + 200; // 200-500ms
        } else if (rand < 0.98) {
          status = "DEGRADED";
          latencyMs = Math.floor(Math.random() * 2000) + 1000; // 1000-3000ms
        } else {
          status = "OUTAGE";
          latencyMs = null;
        }

        observationsToCreate.push({
          serviceSurfaceId: surface.id,
          regionId: region.id,
          status,
          latencyMs,
          errorRate: null,
          observedAt,
        });
      }
    }
  }

  console.log(`📦 Inserting ${observationsToCreate.length} observations in batches of 1000...`);

  for (let i = 0; i < observationsToCreate.length; i += 1000) {
    const batch = observationsToCreate.slice(i, i + 1000);
    await prisma.observation.createMany({
      data: batch,
      skipDuplicates: true,
    });
    console.log(
      `  ✓ Inserted ${Math.min(1000, observationsToCreate.length - i)} observations...`
    );
  }

  console.log(`✅ Created ${observationsToCreate.length} observations`);

  // Seed resolved incidents
  console.log("🔴 Seeding historical incidents...");

  const incidentsToCreate = realisticIncidents.map((incident) => {
    const service = createdServices.find((s) => s.slug === incident.serviceSlug);
    if (!service) throw new Error(`Service not found: ${incident.serviceSlug}`);

    return {
      serviceId: service.id,
      title: incident.title,
      status: "RESOLVED" as const,
      severity: incident.severity as IncidentSeverity,
      startedAt: incident.startedAt,
      resolvedAt: incident.resolvedAt,
      summary: incident.summary,
      sourceBadge: "LIVE_MONITORING" as const,
    };
  });

  await prisma.incident.createMany({
    data: incidentsToCreate,
  });

  console.log(`✅ Created ${incidentsToCreate.length} incidents`);

  console.log("\n✨ Seed complete!");
  console.log(`
📊 Summary:
  - Services: ${createdServices.length}
  - Surfaces: ${createdServices.reduce((acc, s) => acc + s.surfaces.length, 0)}
  - Observations: ${observationsToCreate.length}
  - Incidents: ${incidentsToCreate.length}
  - Regions: 1 (EU)
  `);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
