import type { TopServiceContent } from "@/content/top-services/types";

// DESIGN — enriched service content. Feeds ErrorSignaturesPanel, ProviderSpecificPanel
// and FallbackAlternativesPanel on /[serviceSlug]. Keys are DB Service.slug values and
// MUST exist in the Service table (an orphan key is content for a 404). Keep this file
// under ~3000 lines: start design-2.ts and register it in ./index.ts if it grows.
export const DESIGN: Record<string, TopServiceContent> = {
  gamma: {
    slug: "gamma",
    providerSummary:
      "AI-powered presentation and document generator. Creates slides, docs, and webpages from prompts.",
    docsUrl: "https://gamma.app/help",
    pricingUrl: "https://gamma.app/pricing",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "gamma.app", description: "Web editor and generator", criticality: "critical" },
      { name: "Generation Backend", description: "AI presentation generation", criticality: "critical" },
      { name: "Export Pipeline", description: "PPTX, PDF, and link export", criticality: "high" },
    ],
    knownFailurePatterns: [
      {
        pattern: "Credit depletion",
        scope: "local",
        signal: "User runs out of AI generation credits",
        quickCheck: "Check credit balance; upgrade plan or wait for monthly reset",
      },
      {
        pattern: "Export format issues (PPTX, PDF)",
        scope: "global",
        signal: "Exported file is corrupted or missing slides",
        quickCheck: "Try a different export format; check status for export pipeline",
      },
      {
        pattern: "Template rendering glitches",
        scope: "partial",
        signal: "Layout breaks on specific templates",
        quickCheck: "Switch template; reload the presentation",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Gamma is degraded",
        alternative:
          "Beautiful.ai, Tome, or SlidesAI can reduce downtime for AI presentation generation",
        switchingCost: "low",
      },
    ],
    ecosystemDependencies: [],
    operatorNotes: [],
  },
  "10web-ai": {
    slug: "10web-ai",
    providerSummary:
      "10Web is an AI WordPress website builder with managed hosting: sites are generated by AI, then hosted on 10Web's Google Cloud-based infrastructure. Incidents therefore affect both the builder and customers' live sites.",
    docsUrl: "https://help.10web.io",
    pricingUrl: "https://10web.io/pricing/",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "10Web dashboard and AI builder", description: "Site generation", criticality: "high" },
      { name: "Managed hosting", description: "Customer sites", criticality: "critical" },
    ],
    knownFailurePatterns: [
      {
        pattern: "Hosted sites down or slow",
        scope: "global",
        signal: "Multiple customer sites return errors at once",
        quickCheck: "Check the 10Web dashboard and status announcements; nothing to fix on the site",
      },
      {
        pattern: "AI generation failing while the dashboard works",
        scope: "partial",
        signal: "Site or content generation errors",
        quickCheck: "Retry later; the AI layer is separate from hosting",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "10Web is down",
        alternative: "Hostinger AI, Durable AI or Wix AI (monitored on DownForAI) build and host AI-generated sites",
        switchingCost: "high",
      },
    ],
    ecosystemDependencies: ["Google Cloud infrastructure", "WordPress"],
    operatorNotes: [],
  },
  "adobe-express": {
    slug: "adobe-express",
    providerSummary:
      "Adobe Express is Adobe's quick design tool (web and mobile) with Firefly-powered generation, templates and content scheduling, tied to an Adobe ID. It follows Adobe's status page, and adobe.com refuses automated probes.",
    officialStatusUrl: "https://status.adobe.com",
    docsUrl: "https://www.adobe.com/express/",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "new.express.adobe.com", description: "Web app", criticality: "critical" },
      { name: "Firefly generation", description: "AI features", criticality: "high" },
      { name: "Adobe ID", description: "Sign-in", criticality: "critical" },
    ],
    knownFailurePatterns: [
      {
        pattern: "AI generation failing while editing works",
        scope: "partial",
        signal: "Text-to-image or generative features error; templates and edits save",
        quickCheck: "Check status.adobe.com for a Firefly incident",
      },
      {
        pattern: "Sign-in loop with Adobe ID",
        scope: "local",
        signal: "Login redirects back without signing in",
        quickCheck: "Clear cookies for adobe.com; check the status page for identity issues",
      },
      {
        pattern: "Generative credits exhausted",
        scope: "local",
        signal: "AI features refused with a credit message for your plan",
        quickCheck: "Credits reset monthly; not an outage",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Adobe Express is down",
        alternative: "Canva AI or Kittl (monitored on DownForAI) offer comparable quick design tools",
        switchingCost: "low",
      },
    ],
    ecosystemDependencies: ["Adobe ID", "Adobe Firefly"],
    operatorNotes: [
      "adobe.com blocks automated requests; the Adobe status page is the reliable signal.",
    ],
  },
  "adobe-photoshop-ai": {
    slug: "adobe-photoshop-ai",
    providerSummary:
      "Photoshop's AI features — Generative Fill, Generative Expand, Remove tool — call Adobe Firefly from the desktop, web and mobile apps, gated by generative credits on the Creative Cloud plan. Local editing works offline; the AI features need Adobe's cloud, reported on Adobe's status page.",
    officialStatusUrl: "https://status.adobe.com",
    docsUrl: "https://www.adobe.com/products/photoshop.html",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "Firefly generative services", description: "Generative Fill and friends", criticality: "critical" },
      { name: "Creative Cloud licensing", description: "Sign-in and entitlement", criticality: "critical" },
      { name: "Photoshop app", description: "Local editing", criticality: "medium" },
    ],
    knownFailurePatterns: [
      {
        pattern: "Generative Fill fails while local tools work",
        scope: "partial",
        signal: "Generative features return errors or spin; layers and filters work",
        quickCheck: "Check status.adobe.com for Firefly; retry later",
      },
      {
        pattern: "Generative credits exhausted",
        scope: "local",
        signal: "Generation slows or is refused after the plan's monthly credits",
        quickCheck: "Check the credit balance in the Creative Cloud account",
      },
      {
        pattern: "Licence check failing",
        scope: "local",
        signal: "Photoshop reports it cannot verify the subscription",
        quickCheck: "Sign out and in with the Adobe ID; a grace period keeps the app usable",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Photoshop's AI features are down",
        alternative: "Canva AI or Pixlr AI (monitored on DownForAI) offer generative fill online; Photoshop's manual tools keep working",
        switchingCost: "low",
      },
    ],
    ecosystemDependencies: ["Adobe Firefly", "Creative Cloud licensing"],
    operatorNotes: [
      "adobe.com blocks automated requests; the Adobe status page is the reliable signal.",
    ],
  },
  autodraw: {
    slug: "autodraw",
    providerSummary:
      "AutoDraw is a free Google AI Experiment that turns rough sketches into icons in the browser, with no accounts. As an experiment it can be paused without notice; there is nothing to configure or subscribe to.",
    docsUrl: "https://www.autodraw.com",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "autodraw.com", description: "Web app", criticality: "critical" },
      { name: "Suggestion backend", description: "Sketch recognition", criticality: "critical" },
    ],
    knownFailurePatterns: [
      {
        pattern: "No suggestions appear while drawing",
        scope: "partial",
        signal: "The suggestion bar stays empty for everyone",
        quickCheck: "Retry later; the recognition backend is degraded",
      },
      {
        pattern: "Site unreachable",
        scope: "global",
        signal: "autodraw.com times out",
        quickCheck: "Nothing to fix locally; experiments can be retired",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "AutoDraw is down",
        alternative: "Illustroke or Canva AI (monitored on DownForAI) generate simple icons and illustrations",
        switchingCost: "low",
      },
    ],
    ecosystemDependencies: [],
    operatorNotes: [],
  },
  banani: {
    slug: "banani",
    providerSummary:
      "Banani generates UI designs for apps and websites from text prompts in a web editor, on credit-based plans. It is a small hosted service relaying to AI models for generation.",
    docsUrl: "https://banani.co",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "banani.co web app", description: "Editor", criticality: "critical" },
      { name: "Generation backend", description: "UI generation", criticality: "critical" },
    ],
    knownFailurePatterns: [
      {
        pattern: "Generations fail or hang",
        scope: "partial",
        signal: "Every prompt errors or stays pending",
        quickCheck: "Retry a short prompt; a universal failure is the backend",
      },
      {
        pattern: "Credits exhausted",
        scope: "local",
        signal: "Generation refused with a credit message for your account",
        quickCheck: "Check the balance",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Banani is down",
        alternative: "Uizard, Visily or Creatie (monitored on DownForAI) generate UI designs from text",
        switchingCost: "low",
      },
    ],
    ecosystemDependencies: ["Third-party model providers"],
    operatorNotes: [],
  },
  "beautiful-ai": {
    slug: "beautiful-ai",
    providerSummary:
      "Beautiful.ai is a presentation tool that applies smart design rules and AI generation to slides, on subscription plans. Decks live in Beautiful.ai's cloud; AI generation relays to third-party models.",
    docsUrl: "https://support.beautiful.ai",
    pricingUrl: "https://www.beautiful.ai/pricing",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "beautiful.ai web app", description: "Editor", criticality: "critical" },
      { name: "AI generation", description: "Deck and slide generation", criticality: "high" },
      { name: "Export / sharing", description: "PDF and links", criticality: "medium" },
    ],
    knownFailurePatterns: [
      {
        pattern: "AI generation failing while editing works",
        scope: "partial",
        signal: "Generate errors; existing decks edit normally",
        quickCheck: "Retry later; the AI layer is separate",
      },
      {
        pattern: "Exports stuck",
        scope: "partial",
        signal: "PDF or PowerPoint exports never complete",
        quickCheck: "Try a small deck; a universal stall is the export service",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Beautiful.ai is down",
        alternative: "Gamma, Pitch AI or SlidesAI (monitored on DownForAI) generate presentations",
        switchingCost: "medium",
      },
    ],
    ecosystemDependencies: ["Third-party model providers"],
    operatorNotes: [],
  },
  "brandmark-io": {
    slug: "brandmark-io",
    providerSummary:
      "Brandmark generates logos and brand identities from keywords in a web app, sold as one-time purchases per logo. It is a small hosted generator with one backend.",
    docsUrl: "https://brandmark.io",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "brandmark.io web app", description: "Generator and editor", criticality: "critical" },
      { name: "Generation backend", description: "Logo rendering", criticality: "critical" },
    ],
    knownFailurePatterns: [
      {
        pattern: "Logos not generating",
        scope: "partial",
        signal: "The generator spins without results for everyone",
        quickCheck: "Retry later; a universal failure is the backend",
      },
      {
        pattern: "Purchase not unlocking downloads",
        scope: "local",
        signal: "Files stay locked after payment",
        quickCheck: "Check the confirmation email and contact support; not an outage",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Brandmark is down",
        alternative: "Looka or Logomaster (monitored on DownForAI) generate logos",
        switchingCost: "low",
      },
    ],
    ecosystemDependencies: [],
    operatorNotes: [],
  },
  "builder-ai": {
    slug: "builder-ai",
    providerSummary:
      "Builder.ai sold AI-assisted app development (Builder Studio) to businesses; the company entered insolvency in 2025 and its website no longer answers. Customers' projects and hosting should be considered at risk or discontinued.",
    docsUrl: "https://www.builder.ai",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "builder.ai", description: "Website (unreachable)", criticality: "low" },
      { name: "Builder Studio / customer apps", description: "Discontinued platform", criticality: "medium" },
    ],
    knownFailurePatterns: [
      {
        pattern: "Website unreachable",
        scope: "global",
        signal: "builder.ai does not resolve",
        quickCheck: "Expected after the insolvency",
      },
      {
        pattern: "Customer projects or hosting failing",
        scope: "local",
        signal: "Apps built on the platform lose support or hosting",
        quickCheck: "Export code and assets if still possible; migrate",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "You relied on Builder.ai",
        alternative: "Lovable, Bolt.new or Readdy (monitored on DownForAI) generate apps and sites with AI",
        switchingCost: "high",
      },
    ],
    ecosystemDependencies: [],
    operatorNotes: [
      "The DB website URL is dead and the company is insolvent; consider marking this service inactive.",
    ],
  },
  creatie: {
    slug: "creatie",
    providerSummary:
      "Creatie is an AI-native UI design tool (web) that generates components, icons and layouts from prompts, on freemium plans. Designs sync through Creatie's cloud; generation relays to AI models.",
    docsUrl: "https://creatie.ai",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "creatie.ai web app", description: "Editor", criticality: "critical" },
      { name: "AI generation", description: "Components and layouts", criticality: "high" },
    ],
    knownFailurePatterns: [
      {
        pattern: "AI generation failing while editing works",
        scope: "partial",
        signal: "Generate errors; the canvas works",
        quickCheck: "Retry later; the AI layer is separate",
      },
      {
        pattern: "Files not syncing",
        scope: "partial",
        signal: "Changes do not persist or collaborators see stale content",
        quickCheck: "Reload; if it persists for everyone, the sync backend is degraded",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Creatie is down",
        alternative: "Figma, Motiff or Uizard (monitored on DownForAI) offer UI design with AI features",
        switchingCost: "medium",
      },
    ],
    ecosystemDependencies: ["Third-party model providers"],
    operatorNotes: [],
  },
  "designs-ai": {
    slug: "designs-ai",
    providerSummary:
      "Designs.ai is an AI creative suite (logo, video, speech, banner makers) on subscription plans, with generation on its own backend. Each maker is a separate tool that can fail independently.",
    docsUrl: "https://designs.ai",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "designs.ai web app", description: "Makers", criticality: "critical" },
      { name: "Generation and rendering", description: "Per-tool backends", criticality: "critical" },
    ],
    knownFailurePatterns: [
      {
        pattern: "One maker fails while others work",
        scope: "partial",
        signal: "For example the video maker stalls but the logo maker generates",
        quickCheck: "Try another maker; a single-tool failure is that backend",
      },
      {
        pattern: "Exports stuck",
        scope: "partial",
        signal: "Renders never complete",
        quickCheck: "Try a smaller project; a universal stall is the render service",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Designs.ai is down",
        alternative: "Canva AI or Kittl (monitored on DownForAI) cover logos, banners and marketing visuals",
        switchingCost: "low",
      },
    ],
    ecosystemDependencies: [],
    operatorNotes: [],
  },
  "durable-ai": {
    slug: "durable-ai",
    providerSummary:
      "Durable builds and hosts small-business websites from a few prompts, with CRM and invoicing add-ons; durable.co redirects to durable.com. Incidents affect the builder and customers' hosted sites.",
    docsUrl: "https://help.durable.co",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "Durable dashboard and builder", description: "Site generation", criticality: "high" },
      { name: "Hosted sites", description: "Customer websites", criticality: "critical" },
    ],
    knownFailurePatterns: [
      {
        pattern: "Hosted sites down",
        scope: "global",
        signal: "Customer sites return errors at once",
        quickCheck: "Check Durable's announcements; nothing to fix on the site",
      },
      {
        pattern: "Site generation failing",
        scope: "partial",
        signal: "The builder errors while the dashboard loads",
        quickCheck: "Retry later; the AI layer is separate from hosting",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Durable is down",
        alternative: "Wix AI, Hostinger AI or 10Web AI (monitored on DownForAI) build and host sites with AI",
        switchingCost: "high",
      },
    ],
    ecosystemDependencies: [],
    operatorNotes: [
      "durable.co redirects to durable.com; DownForAI's probe follows the redirect.",
    ],
  },
  figma: {
    slug: "figma",
    providerSummary:
      "Figma is the collaborative design platform (Design, FigJam, Dev Mode, Slides, Make) with AI features layered on top, running as a real-time cloud app. 'Figma down' is one of the most searched outage queries; incidents are published on Figma's own status page.",
    docsUrl: "https://help.figma.com",
    pricingUrl: "https://www.figma.com/pricing/",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "figma.com editor", description: "Design and FigJam files", criticality: "critical" },
      { name: "Real-time sync", description: "Multiplayer", criticality: "critical" },
      { name: "AI features / Figma Make", description: "Generation", criticality: "high" },
    ],
    knownFailurePatterns: [
      {
        pattern: "Files not loading or 'unable to connect'",
        scope: "global",
        signal: "Editors fail to open files for everyone; status.figma.com lists an incident",
        quickCheck: "Check the status page; unsaved changes are kept locally until reconnection",
      },
      {
        pattern: "Multiplayer sync lagging",
        scope: "partial",
        signal: "Collaborators' cursors and edits appear late",
        quickCheck: "Check the status page's sync component",
      },
      {
        pattern: "AI features failing while design works",
        scope: "partial",
        signal: "Figma Make or AI actions error; editing works",
        quickCheck: "Keep designing; the AI layer is separate",
      },
      {
        pattern: "Seat or plan limits",
        scope: "local",
        signal: "AI credits or editor seats exhausted for your team",
        quickCheck: "Check the team's plan usage",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Figma is down",
        alternative: "Motiff or Creatie (monitored on DownForAI) offer Figma-like design tools; Adobe Express covers quick graphics",
        switchingCost: "high",
      },
    ],
    ecosystemDependencies: ["Third-party model providers for AI features"],
    operatorNotes: [
      "Figma publishes its own status page; DownForAI probes figma.com only.",
    ],
  },
  "flair-ai": {
    slug: "flair-ai",
    providerSummary:
      "Flair generates branded product photography from uploaded product images and templates, on credit-based plans. Rendering is a queued job on Flair's servers.",
    docsUrl: "https://flair.ai",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "flair.ai web app", description: "Editor", criticality: "critical" },
      { name: "Render queue", description: "Image generation", criticality: "critical" },
    ],
    knownFailurePatterns: [
      {
        pattern: "Renders stuck",
        scope: "partial",
        signal: "Generations stay pending for everyone",
        quickCheck: "Try a simple template; a universal stall is capacity",
      },
      {
        pattern: "Credits exhausted",
        scope: "local",
        signal: "Generation refused with a credit message for your account",
        quickCheck: "Check the balance",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Flair is down",
        alternative: "Mokker, PhotoRoom or Bria AI (monitored on DownForAI) generate product photos",
        switchingCost: "low",
      },
    ],
    ecosystemDependencies: [],
    operatorNotes: [],
  },
  framer: {
    slug: "framer",
    providerSummary:
      "Framer (this second DB entry tracks the same product as Framer AI in Productivity) is a website builder and design tool with AI generation and its own hosting. Editor incidents affect designers; hosting incidents affect every published site.",
    docsUrl: "https://www.framer.com/help/",
    pricingUrl: "https://www.framer.com/pricing/",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "Framer editor", description: "Design", criticality: "high" },
      { name: "Framer hosting", description: "Published sites", criticality: "critical" },
    ],
    knownFailurePatterns: [
      {
        pattern: "Published sites down",
        scope: "global",
        signal: "Framer-hosted sites return errors at once",
        quickCheck: "Check Framer's status page; nothing to republish",
      },
      {
        pattern: "Publishing stuck",
        scope: "partial",
        signal: "Publish never completes; the live site keeps the last version",
        quickCheck: "Wait for the incident",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Framer is down",
        alternative: "Webflow AI or Vercel (monitored on DownForAI) can host an exported site",
        switchingCost: "high",
      },
    ],
    ecosystemDependencies: [],
    operatorNotes: [
      "Duplicate of the framer-ai entry (Productivity category).",
    ],
  },
  fronty: {
    slug: "fronty",
    providerSummary:
      "Fronty converted image designs into HTML and CSS with AI and offered a no-code editor; fronty.com no longer answers, and the product appears to be discontinued.",
    docsUrl: "https://fronty.com",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "fronty.com", description: "Website (unreachable)", criticality: "low" },
    ],
    knownFailurePatterns: [
      {
        pattern: "Website unreachable",
        scope: "global",
        signal: "fronty.com does not resolve",
        quickCheck: "Treat the product as discontinued",
      },
      {
        pattern: "Exported projects still work",
        scope: "local",
        signal: "Previously exported HTML/CSS is unaffected",
        quickCheck: "Nothing to do; the code is yours",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "You need image-to-code now",
        alternative: "Locofy or Uizard (monitored on DownForAI) convert designs and screenshots to code",
        switchingCost: "low",
      },
    ],
    ecosystemDependencies: [],
    operatorNotes: [
      "The DB website URL is dead; consider marking this service inactive.",
    ],
  },
  "galileo-ai-design": {
    slug: "galileo-ai-design",
    providerSummary:
      "Galileo AI generated UI designs from text; the product was acquired by Google and became Stitch (usegalileo.ai redirects to stitch.withgoogle.com), a Google Labs experiment. Existing Galileo accounts are gone; Stitch is the successor.",
    docsUrl: "https://www.usegalileo.ai",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "usegalileo.ai → stitch.withgoogle.com", description: "Redirect", criticality: "low" },
      { name: "Google Stitch", description: "Successor experiment", criticality: "high" },
    ],
    knownFailurePatterns: [
      {
        pattern: "Old Galileo projects unavailable",
        scope: "global",
        signal: "The original app is gone",
        quickCheck: "Expected after the acquisition; use Stitch",
      },
      {
        pattern: "Stitch quota or region limits",
        scope: "local",
        signal: "Generations refused after the monthly allowance or in unsupported regions",
        quickCheck: "Labs experiments cap usage; not an outage",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Stitch is unavailable",
        alternative: "Uizard, Visily or Banani (monitored on DownForAI) generate UI designs from text",
        switchingCost: "low",
      },
    ],
    ecosystemDependencies: ["Google Labs"],
    operatorNotes: [
      "usegalileo.ai redirects to stitch.withgoogle.com; DownForAI's probe follows the redirect.",
    ],
  },
  "hostinger-ai": {
    slug: "hostinger-ai",
    providerSummary:
      "Hostinger's AI website builder generates sites that run on Hostinger's hosting, sold with hosting plans. Builder incidents affect creation; hosting incidents affect live sites, and Hostinger publishes its own status page.",
    docsUrl: "https://support.hostinger.com",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "Hostinger panel and AI builder", description: "Site creation", criticality: "high" },
      { name: "Hosting", description: "Customer sites", criticality: "critical" },
    ],
    knownFailurePatterns: [
      {
        pattern: "Hosted sites down in a data centre",
        scope: "partial",
        signal: "Sites on one server or region error",
        quickCheck: "Check Hostinger's status page for the data centre",
      },
      {
        pattern: "AI builder generation failing",
        scope: "partial",
        signal: "Site generation errors while the panel works",
        quickCheck: "Retry later; the AI layer is separate from hosting",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Hostinger is down",
        alternative: "10Web AI, Wix AI or Durable AI (monitored on DownForAI) build and host sites",
        switchingCost: "high",
      },
    ],
    ecosystemDependencies: [],
    operatorNotes: [
      "Hostinger publishes its own status page; DownForAI probes hostinger.com only.",
    ],
  },
  illustroke: {
    slug: "illustroke",
    providerSummary:
      "Illustroke generates vector (SVG) illustrations from text prompts in a web app, on credit-based plans. It is a small hosted generator relaying to image models with vectorisation on top.",
    docsUrl: "https://illustroke.com",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "illustroke.com web app", description: "Generator", criticality: "critical" },
      { name: "Generation and vectorisation", description: "Backend", criticality: "critical" },
    ],
    knownFailurePatterns: [
      {
        pattern: "Generations failing",
        scope: "partial",
        signal: "Every prompt errors or hangs",
        quickCheck: "Retry a short prompt; a universal failure is the backend",
      },
      {
        pattern: "Credits exhausted",
        scope: "local",
        signal: "Generation refused with a credit message for your account",
        quickCheck: "Check the balance",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Illustroke is down",
        alternative: "Recraft or Ideogram (monitored on DownForAI) generate vector-style illustrations",
        switchingCost: "low",
      },
    ],
    ecosystemDependencies: ["Third-party image models"],
    operatorNotes: [],
  },
  "interior-ai": {
    slug: "interior-ai",
    providerSummary:
      "Interior AI redesigns rooms from uploaded photos in chosen styles, on a paid plan, run as a small web service by an independent maker. Generation is a queued job on shared GPUs.",
    docsUrl: "https://interiorai.com",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "interiorai.com web app", description: "Upload and render", criticality: "critical" },
      { name: "GPU queue", description: "Room renders", criticality: "critical" },
    ],
    knownFailurePatterns: [
      {
        pattern: "Renders stuck",
        scope: "partial",
        signal: "Uploads never produce a redesign",
        quickCheck: "Try one small photo; a universal stall is capacity",
      },
      {
        pattern: "Plan not recognised",
        scope: "local",
        signal: "Renders refused after payment",
        quickCheck: "Log out and in; contact the maker with the receipt",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Interior AI is down",
        alternative: "RoomGPT (monitored on DownForAI) offers the same room redesign",
        switchingCost: "low",
      },
    ],
    ecosystemDependencies: [],
    operatorNotes: [],
  },
  "khroma-design": {
    slug: "khroma-design",
    providerSummary:
      "Khroma generates colour palettes with an AI that learns your preferences, entirely in the browser after a short training step, free to use. There is very little server dependency, so it rarely 'goes down' beyond the site itself.",
    docsUrl: "https://www.khroma.co",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "khroma.co", description: "Web app", criticality: "critical" },
    ],
    knownFailurePatterns: [
      {
        pattern: "Site unreachable",
        scope: "global",
        signal: "khroma.co times out",
        quickCheck: "Nothing to fix locally",
      },
      {
        pattern: "Training preferences lost",
        scope: "local",
        signal: "The palette generator asks to train again",
        quickCheck: "Preferences live in browser storage; clearing site data resets them",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Khroma is down",
        alternative: "Canva AI or Adobe Express (monitored on DownForAI) include palette tools",
        switchingCost: "low",
      },
    ],
    ecosystemDependencies: [],
    operatorNotes: [],
  },
  "kittel-ai": {
    slug: "kittel-ai",
    providerSummary:
      "Kittl is a browser design platform for logos, merch and marketing visuals with AI generation and vectorisation, on freemium plans. Designs live in Kittl's cloud; AI features relay to image models, and the site blocks direct probes.",
    docsUrl: "https://help.kittl.com",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "kittl.com editor", description: "Web app", criticality: "critical" },
      { name: "AI generation", description: "Images and vectors", criticality: "high" },
      { name: "Exports", description: "Downloads", criticality: "medium" },
    ],
    knownFailurePatterns: [
      {
        pattern: "AI generation failing while editing works",
        scope: "partial",
        signal: "Generate errors; the canvas works",
        quickCheck: "Retry later; the AI layer is separate",
      },
      {
        pattern: "AI credits exhausted",
        scope: "local",
        signal: "Generation refused with a credit message for your plan",
        quickCheck: "Check the plan's AI credits",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Kittl is down",
        alternative: "Canva AI, Adobe Express or Designs.ai (monitored on DownForAI) cover marketing visuals",
        switchingCost: "low",
      },
    ],
    ecosystemDependencies: ["Third-party image models"],
    operatorNotes: [
      "kittl.com refuses automated requests, so DownForAI checks robots.txt reachability only.",
    ],
  },
  locofy: {
    slug: "locofy",
    providerSummary:
      "Locofy converts Figma (and other) designs into front-end code with AI, through a Figma plugin and web app on subscription plans. Conversions run in Locofy's cloud; the docs host was unreachable when this entry was written.",
    docsUrl: "https://www.locofy.ai",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "Locofy plugin and web app", description: "Clients", criticality: "critical" },
      { name: "Conversion backend", description: "Design-to-code", criticality: "critical" },
    ],
    knownFailurePatterns: [
      {
        pattern: "Conversions stuck or failing",
        scope: "partial",
        signal: "Design-to-code runs never finish across projects",
        quickCheck: "Try a single small frame; a universal stall is the backend",
      },
      {
        pattern: "Figma plugin cannot sign in",
        scope: "local",
        signal: "The plugin loops on login",
        quickCheck: "Sign out and in; re-authorise the plugin in Figma",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Locofy is down",
        alternative: "Uizard or Visily (monitored on DownForAI) offer design-to-code and screenshot-to-design; Cursor can generate code from screenshots",
        switchingCost: "medium",
      },
    ],
    ecosystemDependencies: ["Figma plugin platform"],
    operatorNotes: [
      "docs.locofy.ai was unreachable when this entry was written; the docs link points to the main site.",
    ],
  },
  "logomaster-ai": {
    slug: "logomaster-ai",
    providerSummary:
      "Logomaster generates logos and brand kits from a few answers in a web wizard, sold per logo package. It is a small hosted generator with a single backend and checkout.",
    docsUrl: "https://logomaster.ai",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "logomaster.ai web app", description: "Wizard and editor", criticality: "critical" },
      { name: "Checkout and downloads", description: "Purchases", criticality: "high" },
    ],
    knownFailurePatterns: [
      {
        pattern: "Logos not generating",
        scope: "partial",
        signal: "The wizard spins without results",
        quickCheck: "Retry later; a universal failure is the backend",
      },
      {
        pattern: "Downloads locked after purchase",
        scope: "local",
        signal: "Files stay watermarked or locked",
        quickCheck: "Check the confirmation email and contact support",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Logomaster is down",
        alternative: "Looka or Brandmark (monitored on DownForAI) generate logos",
        switchingCost: "low",
      },
    ],
    ecosystemDependencies: [],
    operatorNotes: [],
  },
  looka: {
    slug: "looka",
    providerSummary:
      "Looka generates logos and full brand kits (business cards, social templates) from preferences, sold per logo or by subscription. It sits behind bot protection and runs generation on its own backend.",
    docsUrl: "https://help.looka.com",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "looka.com web app", description: "Generator and editor", criticality: "critical" },
      { name: "Brand kit generation", description: "Assets", criticality: "high" },
    ],
    knownFailurePatterns: [
      {
        pattern: "Logo generation stuck",
        scope: "partial",
        signal: "The generator never returns options for everyone",
        quickCheck: "Retry later; a universal stall is the backend",
      },
      {
        pattern: "Edge challenge or 403",
        scope: "local",
        signal: "A verification page, often on VPNs",
        quickCheck: "Disable the VPN and complete the check",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Looka is down",
        alternative: "Brandmark or Logomaster (monitored on DownForAI) generate logos",
        switchingCost: "low",
      },
    ],
    ecosystemDependencies: [],
    operatorNotes: [
      "looka.com refuses automated requests, so DownForAI checks robots.txt reachability only.",
    ],
  },
  "mockplus-ai": {
    slug: "mockplus-ai",
    providerSummary:
      "Mockplus is a prototyping and design collaboration platform with AI features for generating screens, on subscription plans. The AI product page tracked in the DB currently returns 404; the main app remains at mockplus.com.",
    docsUrl: "https://www.mockplus.com/ai",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "mockplus.com app", description: "Prototyping", criticality: "critical" },
      { name: "AI generation", description: "Screens and components", criticality: "high" },
    ],
    knownFailurePatterns: [
      {
        pattern: "AI generation failing while prototyping works",
        scope: "partial",
        signal: "AI screens error; the editor works",
        quickCheck: "Retry later; the AI layer is separate",
      },
      {
        pattern: "Product page returns 404",
        scope: "local",
        signal: "The /ai marketing page is gone",
        quickCheck: "Use the main site; not an app outage",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Mockplus is down",
        alternative: "Figma, Uizard or Visily (monitored on DownForAI) cover prototyping with AI",
        switchingCost: "medium",
      },
    ],
    ecosystemDependencies: [],
    operatorNotes: [
      "The DB website URL (mockplus.com/ai) answered 404 when this entry was written.",
    ],
  },
  "mokker-ai": {
    slug: "mokker-ai",
    providerSummary:
      "Mokker generates product photography backgrounds from uploaded product shots, on credit-based plans. Rendering is a queued job on Mokker's servers.",
    docsUrl: "https://mokker.ai",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "mokker.ai web app", description: "Upload and render", criticality: "critical" },
      { name: "Render queue", description: "Image generation", criticality: "critical" },
    ],
    knownFailurePatterns: [
      {
        pattern: "Renders stuck",
        scope: "partial",
        signal: "Generations stay pending for everyone",
        quickCheck: "Try one product photo; a universal stall is capacity",
      },
      {
        pattern: "Credits exhausted",
        scope: "local",
        signal: "Generation refused with a credit message for your account",
        quickCheck: "Check the balance",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Mokker is down",
        alternative: "Flair, PhotoRoom or Bria AI (monitored on DownForAI) generate product backgrounds",
        switchingCost: "low",
      },
    ],
    ecosystemDependencies: [],
    operatorNotes: [],
  },
  motiff: {
    slug: "motiff",
    providerSummary:
      "Motiff is a Figma-like UI design tool with AI layout generation and design-system features, running as a real-time cloud app on freemium plans. Its failures are file loading, multiplayer sync and AI generation.",
    docsUrl: "https://www.motiff.com",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "motiff.com editor", description: "Design files", criticality: "critical" },
      { name: "Real-time sync", description: "Multiplayer", criticality: "critical" },
      { name: "AI generation", description: "Layouts and components", criticality: "high" },
    ],
    knownFailurePatterns: [
      {
        pattern: "Files not loading",
        scope: "global",
        signal: "The editor fails to open files for everyone",
        quickCheck: "Wait and reload; unsaved changes are kept locally until reconnection",
      },
      {
        pattern: "AI generation failing while editing works",
        scope: "partial",
        signal: "AI layout errors; the canvas works",
        quickCheck: "Keep designing; the AI layer is separate",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Motiff is down",
        alternative: "Figma or Creatie (monitored on DownForAI) are comparable UI design tools",
        switchingCost: "medium",
      },
    ],
    ecosystemDependencies: ["Third-party model providers"],
    operatorNotes: [],
  },
  "piktochart-ai": {
    slug: "piktochart-ai",
    providerSummary:
      "Piktochart makes infographics, reports and presentations with AI generation in a browser editor, on freemium plans. Documents live in Piktochart's cloud; the site blocks automated probes entirely.",
    docsUrl: "https://support.piktochart.com",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "piktochart.com editor", description: "Web app", criticality: "critical" },
      { name: "AI generation", description: "Infographics from text", criticality: "high" },
      { name: "Exports", description: "PDF and image downloads", criticality: "medium" },
    ],
    knownFailurePatterns: [
      {
        pattern: "AI generation failing while editing works",
        scope: "partial",
        signal: "Generate errors; existing documents edit",
        quickCheck: "Retry later; the AI layer is separate",
      },
      {
        pattern: "Exports stuck",
        scope: "partial",
        signal: "Downloads never complete",
        quickCheck: "Try a single page; a universal stall is the export service",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Piktochart is down",
        alternative: "Canva AI, Napkin AI or Beautiful.ai (monitored on DownForAI) generate visual content",
        switchingCost: "low",
      },
    ],
    ecosystemDependencies: [],
    operatorNotes: [
      "piktochart.com blocks DownForAI's probes (403); the technical signal is unreliable for this service.",
    ],
  },
  "poly-design": {
    slug: "poly-design",
    providerSummary:
      "Poly generates seamless textures and materials for 3D work from text prompts; withpoly.com now redirects to poly.app. Generation is a queued GPU job on Poly's servers.",
    docsUrl: "https://withpoly.com",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "poly.app web app", description: "Generator", criticality: "critical" },
      { name: "GPU queue", description: "Texture renders", criticality: "critical" },
    ],
    knownFailurePatterns: [
      {
        pattern: "Textures stuck generating",
        scope: "partial",
        signal: "Jobs stay pending for everyone",
        quickCheck: "Try a simple prompt; a universal stall is capacity",
      },
      {
        pattern: "Credits exhausted",
        scope: "local",
        signal: "Generation refused with a credit message for your account",
        quickCheck: "Check the balance",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Poly is down",
        alternative: "Meshy or Scenario (monitored on DownForAI) generate 3D assets and textures",
        switchingCost: "medium",
      },
    ],
    ecosystemDependencies: [],
    operatorNotes: [
      "withpoly.com redirects to poly.app; DownForAI's probe follows the redirect.",
    ],
  },
  readdy: {
    slug: "readdy",
    providerSummary:
      "Readdy generates websites and app designs from text descriptions and can publish them, on credit-based plans. Generation is a model job; publishing depends on Readdy's hosting.",
    docsUrl: "https://readdy.ai",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "readdy.ai web app", description: "Generator", criticality: "critical" },
      { name: "Generation backend", description: "Design generation", criticality: "critical" },
      { name: "Published sites", description: "Hosting", criticality: "high" },
    ],
    knownFailurePatterns: [
      {
        pattern: "Generations failing or slow",
        scope: "partial",
        signal: "Every prompt errors or hangs",
        quickCheck: "Retry a short prompt; a universal failure is the backend",
      },
      {
        pattern: "Published sites down",
        scope: "global",
        signal: "Readdy-hosted sites return errors",
        quickCheck: "Export the code if possible; hosting is Readdy's",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Readdy is down",
        alternative: "Lovable, Bolt.new or Durable AI (monitored on DownForAI) generate and host sites",
        switchingCost: "medium",
      },
    ],
    ecosystemDependencies: ["Third-party model providers"],
    operatorNotes: [],
  },
  "recast-studio": {
    slug: "recast-studio",
    providerSummary:
      "Recast Studio turns podcasts and long videos into short social clips, blog posts and show notes with AI, on subscription plans. Its jobs are long processing runs on uploaded media.",
    docsUrl: "https://recast.studio",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "recast.studio web app", description: "Projects", criticality: "critical" },
      { name: "Processing pipeline", description: "Clip and text generation", criticality: "critical" },
    ],
    knownFailurePatterns: [
      {
        pattern: "Episodes stuck processing",
        scope: "partial",
        signal: "Uploads never produce clips",
        quickCheck: "Try a short file; a universal stall is the pipeline",
      },
      {
        pattern: "Link import failing",
        scope: "local",
        signal: "YouTube or RSS imports error",
        quickCheck: "Upload the file directly",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Recast Studio is down",
        alternative: "Opus Clip or Munch (monitored on DownForAI) repurpose long videos into clips",
        switchingCost: "low",
      },
    ],
    ecosystemDependencies: [],
    operatorNotes: [
      "Categorised under Design in DownForAI's database although it is a video repurposing tool.",
    ],
  },
  relume: {
    slug: "relume",
    providerSummary:
      "Relume generates website sitemaps and wireframes with AI and provides a large component library for Figma and Webflow, on subscription plans; relume.io redirects to relume.ai. Generation relays to AI models.",
    docsUrl: "https://www.relume.io",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "relume.ai app", description: "Site builder", criticality: "critical" },
      { name: "AI generation", description: "Sitemaps and wireframes", criticality: "high" },
      { name: "Library and plugins", description: "Figma / Webflow exports", criticality: "medium" },
    ],
    knownFailurePatterns: [
      {
        pattern: "AI generation failing",
        scope: "partial",
        signal: "Sitemap or wireframe generation errors for everyone",
        quickCheck: "Retry later; the AI layer is separate from the library",
      },
      {
        pattern: "Figma or Webflow export failing",
        scope: "local",
        signal: "Copying to Figma or Webflow errors",
        quickCheck: "Re-authorise the plugin or app",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Relume is down",
        alternative: "Uizard or Visily (monitored on DownForAI) generate wireframes with AI",
        switchingCost: "medium",
      },
    ],
    ecosystemDependencies: ["Figma and Webflow platforms", "Third-party model providers"],
    operatorNotes: [
      "relume.io redirects to relume.ai; DownForAI's probe follows the redirect.",
    ],
  },
  roomgpt: {
    slug: "roomgpt",
    providerSummary:
      "RoomGPT redesigns rooms from photos in chosen themes, originally an open-source demo turned paid app. Generation is a queued job on hosted GPUs.",
    docsUrl: "https://www.roomgpt.io",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "roomgpt.io web app", description: "Upload and render", criticality: "critical" },
      { name: "GPU queue", description: "Room renders", criticality: "critical" },
    ],
    knownFailurePatterns: [
      {
        pattern: "Renders stuck or failing",
        scope: "partial",
        signal: "Uploads never produce a redesign",
        quickCheck: "Try one photo; a universal stall is capacity",
      },
      {
        pattern: "Credits exhausted",
        scope: "local",
        signal: "Generation refused with a credit message for your account",
        quickCheck: "Check the balance",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "RoomGPT is down",
        alternative: "Interior AI (monitored on DownForAI) offers the same room redesign",
        switchingCost: "low",
      },
    ],
    ecosystemDependencies: [],
    operatorNotes: [],
  },
  "squarespace-ai": {
    slug: "squarespace-ai",
    providerSummary:
      "Squarespace's AI features (site generation with Blueprint, AI copy, image tools) run inside the Squarespace builder and hosting. Incidents affect the editor and customers' live sites, and Squarespace publishes its own status page.",
    docsUrl: "https://support.squarespace.com",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "Squarespace editor", description: "Site building", criticality: "high" },
      { name: "Squarespace hosting", description: "Customer sites", criticality: "critical" },
      { name: "AI features", description: "Blueprint and AI writer", criticality: "medium" },
    ],
    knownFailurePatterns: [
      {
        pattern: "Hosted sites down or slow",
        scope: "global",
        signal: "Customer sites error at once; status.squarespace.com lists an incident",
        quickCheck: "Check the status page; nothing to fix on the site",
      },
      {
        pattern: "AI writer failing while editing works",
        scope: "partial",
        signal: "AI copy generation errors; the editor works",
        quickCheck: "Keep editing; the AI layer is separate",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Squarespace is down",
        alternative: "Wix AI, Webflow AI or Framer (monitored on DownForAI) build and host sites",
        switchingCost: "high",
      },
    ],
    ecosystemDependencies: [],
    operatorNotes: [
      "Squarespace publishes its own status page; DownForAI probes squarespace.com only.",
    ],
  },
  uizard: {
    slug: "uizard",
    providerSummary:
      "Uizard generates wireframes and UI designs from text, sketches and screenshots in a web editor, on freemium plans. Generation relays to AI models; the help site was unreachable when this entry was written.",
    docsUrl: "https://uizard.io",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "uizard.io editor", description: "Web app", criticality: "critical" },
      { name: "AI generation", description: "Screens from text and images", criticality: "high" },
    ],
    knownFailurePatterns: [
      {
        pattern: "AI generation failing while editing works",
        scope: "partial",
        signal: "Autodesigner errors; the editor works",
        quickCheck: "Retry later; the AI layer is separate",
      },
      {
        pattern: "Monthly generation limit reached",
        scope: "local",
        signal: "Generation refused with a plan message",
        quickCheck: "Free plans cap AI generations",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Uizard is down",
        alternative: "Visily, Banani or Creatie (monitored on DownForAI) generate UI designs",
        switchingCost: "low",
      },
    ],
    ecosystemDependencies: ["Third-party model providers"],
    operatorNotes: [
      "help.uizard.io was unreachable when this entry was written; the docs link points to the main site.",
    ],
  },
  viesus: {
    slug: "viesus",
    providerSummary:
      "Viesus is an automatic image-enhancement engine (cloud API and on-prem) used by photo services and printers to improve photos at scale. Its users are integrators; incidents are API errors or processing delays.",
    docsUrl: "https://www.viesus.com",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "Viesus Cloud API", description: "Enhancement endpoints", criticality: "critical" },
      { name: "On-prem deployments", description: "Customer-run", criticality: "medium" },
    ],
    knownFailurePatterns: [
      {
        pattern: "API processing slow or failing",
        scope: "partial",
        signal: "Enhancement calls time out across images",
        quickCheck: "Retry with backoff; contact support for the cloud service",
      },
      {
        pattern: "Credits exhausted",
        scope: "local",
        signal: "Requests rejected with a balance message",
        quickCheck: "Check the account's balance",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Viesus is down",
        alternative: "Let's Enhance or Topaz Photo AI (monitored on DownForAI) enhance photos, with APIs or desktop",
        switchingCost: "medium",
      },
    ],
    ecosystemDependencies: [],
    operatorNotes: [],
  },
  visily: {
    slug: "visily",
    providerSummary:
      "Visily is an AI-first design tool for wireframes and mockups, with screenshot-to-design and text-to-design, on freemium plans. Designs live in Visily's cloud; generation relays to AI models.",
    docsUrl: "https://www.visily.ai",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "visily.ai editor", description: "Web app", criticality: "critical" },
      { name: "AI generation", description: "Screens from text and screenshots", criticality: "high" },
    ],
    knownFailurePatterns: [
      {
        pattern: "AI generation failing while editing works",
        scope: "partial",
        signal: "Generate errors; the canvas works",
        quickCheck: "Retry later; the AI layer is separate",
      },
      {
        pattern: "Files not syncing",
        scope: "partial",
        signal: "Changes do not persist or collaborators see stale content",
        quickCheck: "Reload; if it persists for everyone, the sync backend is degraded",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Visily is down",
        alternative: "Uizard, Banani or Figma (monitored on DownForAI) cover wireframes and UI design",
        switchingCost: "low",
      },
    ],
    ecosystemDependencies: ["Third-party model providers"],
    operatorNotes: [],
  },
  "webflow-ai": {
    slug: "webflow-ai",
    providerSummary:
      "Webflow is a professional website builder and hosting platform with AI-assisted design and content features. Designer incidents affect builders; hosting and CDN incidents affect every published site, and Webflow publishes its own status page.",
    docsUrl: "https://help.webflow.com",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "Webflow Designer", description: "Site building", criticality: "high" },
      { name: "Webflow hosting / CDN", description: "Published sites", criticality: "critical" },
      { name: "AI features", description: "Assistant and generation", criticality: "medium" },
    ],
    knownFailurePatterns: [
      {
        pattern: "Published sites down",
        scope: "global",
        signal: "Webflow-hosted sites error at once; status.webflow.com lists an incident",
        quickCheck: "Check the status page; nothing to republish",
      },
      {
        pattern: "Publishing stuck",
        scope: "partial",
        signal: "Publish never completes; live sites keep the last version",
        quickCheck: "Wait for the incident",
      },
      {
        pattern: "AI features failing while the Designer works",
        scope: "partial",
        signal: "AI assistant errors; design and publish work",
        quickCheck: "Keep working; the AI layer is separate",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Webflow is down",
        alternative: "Framer or Squarespace AI (monitored on DownForAI) build and host sites; Vercel can host an export",
        switchingCost: "high",
      },
    ],
    ecosystemDependencies: [],
    operatorNotes: [
      "Webflow publishes its own status page; DownForAI probes webflow.com only.",
    ],
  },
  "wix-ai": {
    slug: "wix-ai",
    providerSummary:
      "Wix's AI (site generation, AI writer, image tools) runs inside the Wix editor and hosting used by millions of sites. Editor incidents affect builders; hosting incidents affect live sites, and Wix publishes its own status page.",
    docsUrl: "https://support.wix.com",
    communityLinks: [],
    monitoredSurfaces: [
      { name: "Wix editor", description: "Site building", criticality: "high" },
      { name: "Wix hosting", description: "Customer sites", criticality: "critical" },
      { name: "AI features", description: "Generation and writer", criticality: "medium" },
    ],
    knownFailurePatterns: [
      {
        pattern: "Hosted sites down or slow",
        scope: "global",
        signal: "Wix sites error at once; status.wix.com lists an incident",
        quickCheck: "Check the status page; nothing to fix on the site",
      },
      {
        pattern: "AI generation failing while editing works",
        scope: "partial",
        signal: "AI site or text generation errors; the editor works",
        quickCheck: "Keep editing; the AI layer is separate",
      },
    ],
    fallbackAlternatives: [
      {
        scenario: "Wix is down",
        alternative: "Squarespace AI, Hostinger AI or Durable AI (monitored on DownForAI) build and host sites",
        switchingCost: "high",
      },
    ],
    ecosystemDependencies: [],
    operatorNotes: [
      "Wix publishes its own status page; DownForAI probes wix.com only.",
    ],
  },
};
